export const ACTIVITY_PLAN_ITEMS = [
  {
    "code": "A00",
    "sectionCode": "AP",
    "sortOrder": 1,
    "tomeSection": "Apresentação",
    "title": "Apresentação geral do Estudo e arquitetura de publicação",
    "summary": "Apresentar o objetivo, a metodologia, a equipe, a relação entre os Relatórios 1 e 2, a estrutura do Portal Naval e a lógica do banco de dados. Esta atividade deve funcionar como porta de entrada pública para o estudo.",
    "functionalResponsible": "M3",
    "support": "M1; M2",
    "portalDeliverable": "Página de apresentação; ficha do estudo; mapa de tomos; glossário inicial.",
    "dependencies": "Definição da identidade editorial, nomes dos membros e validação da arquitetura do portal.",
    "keywords": "Estudo BNDES; governança; metodologia; portal naval",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A01",
    "sectionCode": "I.1",
    "sortOrder": 2,
    "tomeSection": "Tomo I — Introdução",
    "title": "Introdução, objetivos e escopo do Relatório 1",
    "summary": "Delimitar o problema de pesquisa, os objetivos de diagnóstico e cenários, os ciclos históricos analisados e os segmentos abrangidos: navios, embarcações fluviais, offshore, módulos, reparo, descomissionamento e desmantelamento.",
    "functionalResponsible": "M2",
    "support": "M1; M3",
    "portalDeliverable": "Resumo executivo do tomo; escopo; mapa de capítulos; critérios de leitura.",
    "dependencies": "Aprovação dos limites analíticos e da nomenclatura dos segmentos.",
    "keywords": "introdução; escopo; diagnóstico; cenários",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A02",
    "sectionCode": "I.2",
    "sortOrder": 3,
    "tomeSection": "Tomo I — Economia Marítima",
    "title": "Economia marítima e setores geradores de demanda",
    "summary": "Explicar a inter-relação entre indústria naval, marinha mercante, óleo e gás, energia, pesca e defesa, ressaltando a natureza estratégica da economia do mar e as mudanças econômicas, geopolíticas, ambientais, regulatórias e tecnológicas.",
    "functionalResponsible": "M2",
    "support": "M1; M3",
    "portalDeliverable": "Página temática; diagrama de inter-relações; síntese de oportunidades e desafios.",
    "dependencies": "Base conceitual e taxonomia setorial aprovadas.",
    "keywords": "economia do mar; demanda; setores marítimos; estratégia",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A03",
    "sectionCode": "I.3",
    "sortOrder": 4,
    "tomeSection": "Tomo I — Transporte Marítimo Mundial",
    "title": "Mercados mundiais de transporte marítimo",
    "summary": "Analisar a organização dos mercados internacionais, os principais segmentos de carga, fluxos, tipos de navios, bandeiras, fretes, preços, carteiras de encomendas, regulação e tendências ambientais, econômicas e geopolíticas.",
    "functionalResponsible": "M2",
    "support": "M1",
    "portalDeliverable": "Dataset de mercados e frotas; gráficos de fluxos e segmentos; nota de tendências.",
    "dependencies": "Definição das fontes, períodos e unidades de medida para comparação internacional.",
    "keywords": "transporte marítimo; frota; fretes; comércio internacional",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A04",
    "sectionCode": "I.4",
    "sortOrder": 5,
    "tomeSection": "Tomo I — Transporte Marítimo no Brasil",
    "title": "Marinha mercante e transporte marítimo brasileiro",
    "summary": "Descrever a evolução da marinha mercante brasileira, os fluxos de cabotagem e longo curso, empresas, frotas, bandeiras, afretamento, infraestrutura, custos diferenciais e gargalos, convertendo o diagnóstico em cenários de demanda naval.",
    "functionalResponsible": "M2",
    "support": "M3; M1",
    "portalDeliverable": "Página Brasil; cadastro de empresas/frotas; quadro de gargalos; cenários de construção, reparo e modernização.",
    "dependencies": "Compatibilização com dados de transporte e com o capítulo de políticas brasileiras.",
    "keywords": "marinha mercante; cabotagem; longo curso; afretamento",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A05",
    "sectionCode": "I.5",
    "sortOrder": 6,
    "tomeSection": "Tomo I — Transporte Hidroviário Interior",
    "title": "Bacias, fluxos e demanda por embarcações fluviais",
    "summary": "Mapear bacias, infraestrutura, fluxos de carga e passageiros, empresas, frotas, multimodalidade, impactos ambientais e papel da navegação no desenvolvimento regional, estimando a demanda por embarcações fluviais.",
    "functionalResponsible": "M2",
    "support": "M1; M3",
    "portalDeliverable": "Mapa temático; tabela de bacias e fluxos; cenário de demanda fluvial; ficha regional.",
    "dependencies": "Disponibilidade de dados por bacia e harmonização com o diagnóstico de estaleiros fluviais.",
    "keywords": "hidrovias; navegação interior; Amazônia; desenvolvimento regional",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A06",
    "sectionCode": "I.6",
    "sortOrder": 7,
    "tomeSection": "Tomo I — Óleo e Gás Offshore",
    "title": "Mercado mundial de óleo e gás offshore e unidades de E&P",
    "summary": "Analisar regiões produtoras, empresas, marcos regulatórios, tipos de unidades flutuantes, operação dos campos e mercados de construção, afretamento, conversão e descomissionamento, com atenção a FPSO e sondas.",
    "functionalResponsible": "M2",
    "support": "M1; M3",
    "portalDeliverable": "Página de mercado offshore; quadro de unidades; séries de demanda; matriz de tendências.",
    "dependencies": "Integração com descarbonização e com a avaliação de capacidade de fabricação e integração de módulos.",
    "keywords": "offshore; óleo e gás; FPSO; sondas; descomissionamento",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A07",
    "sectionCode": "I.6",
    "sortOrder": 8,
    "tomeSection": "Tomo I — Offshore no Brasil",
    "title": "Atividade offshore brasileira e demanda associada",
    "summary": "Caracterizar campos, empresas, participação de mercado, unidades em operação, perspectivas e descomissionamento no Brasil, traduzindo essas informações em demanda potencial para construção, fabricação, integração de módulos e conversão.",
    "functionalResponsible": "M2",
    "support": "M1; M3",
    "portalDeliverable": "Painel Brasil offshore; inventário de unidades; cenários de demanda; mapa de oportunidades.",
    "dependencies": "Atualização das bases de campos, unidades e projetos em andamento.",
    "keywords": "offshore Brasil; unidades flutuantes; módulos; demanda",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A08",
    "sectionCode": "I.6",
    "sortOrder": 9,
    "tomeSection": "Tomo I — Apoio Offshore",
    "title": "Aliviadores e embarcações de apoio offshore",
    "summary": "Comparar o mercado mundial e brasileiro de navios aliviadores e OSV, incluindo tipos de embarcação, padrões operacionais, afretamento, preços, regulação, empresas, frotas e verticalização.",
    "functionalResponsible": "M1",
    "support": "M2; M3",
    "portalDeliverable": "Catálogo de tipos de embarcação; comparação internacional; cenários por classe de OSV.",
    "dependencies": "Definição das classes de embarcações e das métricas de comparação.",
    "keywords": "aliviadores; OSV; apoio marítimo; apoio portuário",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A09",
    "sectionCode": "I.6",
    "sortOrder": 10,
    "tomeSection": "Tomo I — Energia Eólica Offshore",
    "title": "Eólica offshore e embarcações especializadas",
    "summary": "Avaliar a evolução e as perspectivas da geração eólica offshore no Brasil, identificando instalações, embarcações de apoio e de transporte de turbinas e os requisitos para uma cadeia naval associada.",
    "functionalResponsible": "M1",
    "support": "M2; M3",
    "portalDeliverable": "Nota temática; tipologia de embarcações; mapa de oportunidades; cenários de demanda.",
    "dependencies": "Compatibilização com regulação energética e com a infraestrutura portuária.",
    "keywords": "eólica offshore; energia oceânica; embarcações especializadas",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A10",
    "sectionCode": "I.7",
    "sortOrder": 11,
    "tomeSection": "Tomo I — Defesa Naval",
    "title": "Construção naval militar: programas, capacitação tecnológica e demanda",
    "summary": "Examinar os programas de construção naval militar brasileiros e experiências internacionais, com foco em offset, conteúdo local, clusters produtivos, capacitação tecnológica, inovação e cenários de demanda por navios e embarcações militares.",
    "functionalResponsible": "M1",
    "support": "M3; M2",
    "portalDeliverable": "Página de defesa naval; matriz de programas; lições internacionais; cenário de demanda.",
    "dependencies": "Definição do nível de abertura das informações sensíveis e validação institucional.",
    "keywords": "defesa naval; offset; clusters; conteúdo local",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A11",
    "sectionCode": "I.8",
    "sortOrder": 12,
    "tomeSection": "Tomo I — Descarbonização Marítima",
    "title": "Metas, estratégias e governança da descarbonização marítima",
    "summary": "Sistematizar o processo mundial de descarbonização, as metas da IMO e as estratégias nacionais e regionais, identificando respostas de armadores, operadores, portos e fornecedores de energia.",
    "functionalResponsible": "M3",
    "support": "M1; M2",
    "portalDeliverable": "Linha do tempo regulatória; quadro de estratégias; mapa de atores; resumo público.",
    "dependencies": "Validação das fontes regulatórias e da terminologia de transição energética.",
    "keywords": "descarbonização; IMO; regulação; transição energética",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A12",
    "sectionCode": "I.8",
    "sortOrder": 13,
    "tomeSection": "Tomo I — Descarbonização Marítima",
    "title": "Tecnologias de eficiência e combustíveis alternativos",
    "summary": "Classificar tecnologias emergentes de projeto, propulsão, operação, digitalização e infraestrutura de abastecimento aplicáveis a embarcações e unidades offshore, indicando maturidade e implicações industriais.",
    "functionalResponsible": "M1",
    "support": "M3; M2",
    "portalDeliverable": "Matriz tecnológica; fichas de tecnologias; glossário; quadro de infraestrutura.",
    "dependencies": "Critérios comuns de maturidade tecnológica, eficiência e aplicabilidade.",
    "keywords": "combustíveis alternativos; eficiência energética; digitalização",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A13",
    "sectionCode": "I.8",
    "sortOrder": 14,
    "tomeSection": "Tomo I — Descarbonização Marítima",
    "title": "Frota, mercados e retrofitting",
    "summary": "Avaliar a situação da frota global e brasileira quanto a combustíveis alternativos e tecnologias de eficiência, estimando os efeitos da transição sobre mercados, renovação de frotas, novas construções e retrofitting.",
    "functionalResponsible": "M2",
    "support": "M1; M3",
    "portalDeliverable": "Dataset de frota; gráficos de renovação; matriz de retrofitting; cenários.",
    "dependencies": "Integração dos dados de frota com os cenários de demanda e capacidade produtiva.",
    "keywords": "frota; retrofitting; renovação; eficiência",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "A14",
    "sectionCode": "I.8",
    "sortOrder": 15,
    "tomeSection": "Tomo I — Descarbonização Marítima",
    "title": "Potencial brasileiro em combustíveis renováveis e logística verde",
    "summary": "Analisar o potencial competitivo do Brasil na produção e no uso de combustíveis renováveis para o transporte marítimo e identificar necessidades de infraestrutura portuária e logística verde.",
    "functionalResponsible": "M3",
    "support": "M1; M2",
    "portalDeliverable": "Mapa de oportunidades; requisitos de infraestrutura; síntese de desafios regulatórios e logísticos.",
    "dependencies": "Integração com políticas industriais, energia, portos e cenários de demanda.",
    "keywords": "combustíveis renováveis; portos; logística verde; Brasil",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "B01",
    "sectionCode": "II.1",
    "sortOrder": 16,
    "tomeSection": "Tomo II — Construção Naval Mundial",
    "title": "Estrutura, produção e competitividade da construção naval mundial",
    "summary": "Analisar a trajetória e a estrutura atual da construção naval mundial, incluindo produção, capacidade, estaleiros, grupos empresariais, especialização, seriação, tecnologia, cadeia produtiva, protecionismo e impactos recentes.",
    "functionalResponsible": "M1",
    "support": "M2; M3",
    "portalDeliverable": "Banco comparativo de estaleiros; ranking por segmento; mapas de capacidade; síntese de competitividade.",
    "dependencies": "Definição da tipologia de estaleiros, segmentos e indicadores comparáveis.",
    "keywords": "construção naval mundial; estaleiros; capacidade; competitividade",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "B02",
    "sectionCode": "II.2",
    "sortOrder": 17,
    "tomeSection": "Tomo II — Experiências Internacionais",
    "title": "Casos nacionais de desenvolvimento da construção naval",
    "summary": "Comparar China, Coreia do Sul, Japão, Singapura, Estados Unidos, países europeus, Índia, Vietnã e Indonésia quanto a estrutura empresarial, tecnologia, fornecedores, recursos humanos, produtividade, inserção internacional e estratégias de catching-up.",
    "functionalResponsible": "M3",
    "support": "M1; M2; consultorias internacionais",
    "portalDeliverable": "Fichas de casos; matriz comparativa de políticas e resultados; registro de visitas técnicas.",
    "dependencies": "Consolidação dos roteiros e evidências das missões internacionais documentadas no calendário do estudo.",
    "keywords": "China; Coreia; Japão; Índia; catching-up; política industrial",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "B03",
    "sectionCode": "II.3",
    "sortOrder": 18,
    "tomeSection": "Tomo II — Construção Naval no Brasil",
    "title": "Histórico e desempenho da construção naval e offshore brasileira",
    "summary": "Reconstituir a evolução da indústria moderna, planos e programas, ciclos de 1970–1980 e 2000–2010, construção offshore e militar, embarcações fluviais, estrutura empresarial, contratos, preços, prazos, produção e fatores explicativos.",
    "functionalResponsible": "M1",
    "support": "M2; M3",
    "portalDeliverable": "Linha do tempo; base histórica de projetos; diagnóstico de sucessos e falhas; página Brasil.",
    "dependencies": "Harmonização dos períodos históricos e das definições de produção e capacidade.",
    "keywords": "construção naval brasileira; ciclos; offshore; histórico",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "B04",
    "sectionCode": "II.4",
    "sortOrder": 19,
    "tomeSection": "Tomo II — Estaleiros Brasileiros",
    "title": "Inventário nacional de estaleiros e instalações",
    "summary": "Levantar estaleiros e instalações de construção, fabricação e integração de módulos, reparo, conversão e desmonte, em operação ou não, registrando localização, organização, infraestrutura e especialização.",
    "functionalResponsible": "M1",
    "support": "M2; M3; equipes de campo",
    "portalDeliverable": "Cadastro georreferenciado de instalações; fichas padronizadas; documentação de visitas.",
    "dependencies": "Definição dos campos obrigatórios do cadastro e protocolo de validação de campo.",
    "keywords": "estaleiros; instalações; cadastro; georreferenciamento",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "B05",
    "sectionCode": "II.4",
    "sortOrder": 20,
    "tomeSection": "Tomo II — Estaleiros Brasileiros",
    "title": "Capacidade produtiva, carteira e potencial de reativação",
    "summary": "Avaliar capacidade produtiva, engenharia, processos, gestão, carteira, desempenho, cadeia regional e potencial de modernização, reativação ou adaptação dos estaleiros para segmentos viáveis.",
    "functionalResponsible": "M1",
    "support": "M2; M3",
    "portalDeliverable": "Matriz de capacidade; avaliação de potencial; fichas de estaleiro; mapa de oportunidades.",
    "dependencies": "Resultados do inventário B04 e critérios de avaliação tecnológica e econômica.",
    "keywords": "capacidade produtiva; modernização; reativação; estaleiros",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "B06",
    "sectionCode": "II.5",
    "sortOrder": 21,
    "tomeSection": "Tomo II — Reparo e Descomissionamento",
    "title": "Reparo, conversão, desmantelamento e descomissionamento",
    "summary": "Analisar o mercado mundial, a regulação e a capacidade brasileira para reparo, docagem, conversão, modernização, retrofitting e desmantelamento, considerando a competição internacional.",
    "functionalResponsible": "M1",
    "support": "M2; M3",
    "portalDeliverable": "Página de serviços navais; matriz de demanda e capacidade; oportunidades e riscos regulatórios.",
    "dependencies": "Integração com o inventário de instalações e com a agenda offshore.",
    "keywords": "reparo; conversão; docagem; desmantelamento",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "B07",
    "sectionCode": "II.6",
    "sortOrder": 22,
    "tomeSection": "Tomo II — Cadeia Produtiva",
    "title": "Cadeia de suprimentos e conteúdo nacional",
    "summary": "Comparar a nacionalização de componentes nos principais países produtores e mapear, no Brasil, localização, capacidade, dependências externas, lacunas tecnológicas e relações entre estaleiros e fornecedores.",
    "functionalResponsible": "M3",
    "support": "M1; M2",
    "portalDeliverable": "Mapa da cadeia; cadastro de fornecedores; matriz de conteúdo nacional; análise por cadeia civil, fluvial, offshore e militar.",
    "dependencies": "Critérios de classificação de componentes, fornecedores e índice de nacionalização.",
    "keywords": "cadeia produtiva; navipeças; conteúdo nacional; siderurgia",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "B08",
    "sectionCode": "II.7",
    "sortOrder": 23,
    "tomeSection": "Tomo II — Tecnologia e Recursos Humanos",
    "title": "Padrão tecnológico, P&D e formação profissional",
    "summary": "Avaliar a capacitação em engenharia de produto e processo, gestão da produção, perfil da força de trabalho, sistema de P&D e formação de recursos humanos de nível básico, técnico e superior.",
    "functionalResponsible": "M1",
    "support": "M3; M2",
    "portalDeliverable": "Matriz de competências; mapa de instituições de P&D e formação; lacunas de qualificação.",
    "dependencies": "Definição das categorias de competência e das fontes institucionais.",
    "keywords": "tecnologia; P&D; recursos humanos; qualificação",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "B09",
    "sectionCode": "II.8",
    "sortOrder": 24,
    "tomeSection": "Tomo II — Produtividade e Competitividade",
    "title": "Indicadores, benchmarking e inserção competitiva",
    "summary": "Desenvolver metodologia de avaliação tecnológica e indicadores simplificados de desempenho, comparando classes de estaleiros mundiais e brasileiros e propondo alternativas de inserção competitiva, metas e prioridades.",
    "functionalResponsible": "M1",
    "support": "M2; M3",
    "portalDeliverable": "Metodologia; painel de indicadores; benchmarking; fichas de posicionamento competitivo.",
    "dependencies": "Disponibilidade e comparabilidade dos dados de produtividade, capacidade e desempenho.",
    "keywords": "produtividade; benchmarking; desempenho; competitividade",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "B10",
    "sectionCode": "II.9",
    "sortOrder": 25,
    "tomeSection": "Tomo II — Descarbonização Industrial",
    "title": "Oportunidades e desafios para a indústria naval",
    "summary": "Diagnosticar as mudanças exigidas pela transição energética no projeto, produção, conversão e reparo, incluindo novos combustíveis, eficiência, captura de carbono e descarbonização dos processos de construção.",
    "functionalResponsible": "M1",
    "support": "M2; M3",
    "portalDeliverable": "Matriz de competências e tecnologias; mapa de lacunas industriais; agenda de oportunidades e desafios.",
    "dependencies": "Integração com A11–A14 e com a avaliação da base produtiva.",
    "keywords": "descarbonização industrial; projeto naval; construção limpa",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "C01",
    "sectionCode": "III.1",
    "sortOrder": 26,
    "tomeSection": "Tomo III — Fundamentos",
    "title": "Fundamentos e tendências: política industrial e política marítima",
    "summary": "Revisar literatura, conceitos e justificativas econômicas da política industrial, políticas horizontais e setoriais, transformações ambientais e geopolíticas, políticas brasileiras, políticas marítimas e navais, instrumentos da NIB e fomento à descarbonização marítima.",
    "functionalResponsible": "M3",
    "support": "M2; M1",
    "portalDeliverable": "Marco conceitual; linha do tempo; matriz de instrumentos; síntese para o Portal Naval.",
    "dependencies": "Definição da metodologia de análise de políticas setoriais.",
    "keywords": "política industrial; política marítima; governança",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "C02",
    "sectionCode": "III.2",
    "sortOrder": 27,
    "tomeSection": "Tomo III — Marinha Mercante no Mundo",
    "title": "Políticas mundiais de marinha mercante",
    "summary": "Comparar justificativas, modelos e instrumentos de proteção e incentivo em países marítimos, abrangendo registros, financiamento, subsídios, incentivos fiscais, reserva de mercado, tripulação e desenvolvimento tecnológico.",
    "functionalResponsible": "M3",
    "support": "M2; M1",
    "portalDeliverable": "Fichas de países; matriz de instrumentos; casos de sucesso e falha; comparativo internacional.",
    "dependencies": "Critérios homogêneos para análise dos países e seleção dos casos relevantes.",
    "keywords": "marinha mercante; incentivos; registros; financiamento",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "C03",
    "sectionCode": "III.3",
    "sortOrder": 28,
    "tomeSection": "Tomo III — Construção Naval no Mundo",
    "title": "Políticas mundiais de construção naval",
    "summary": "Analisar a relação entre políticas de construção naval e transporte marítimo, os ciclos de industrialização, a realocação geográfica, os mecanismos de proteção, cooperação e catching-up tecnológico.",
    "functionalResponsible": "M3",
    "support": "M1; M2",
    "portalDeliverable": "Matriz internacional de políticas; fichas de casos; lições aplicáveis ao Brasil.",
    "dependencies": "Integração com B01, B02 e a evidência das visitas internacionais.",
    "keywords": "política naval; construção naval; catching-up; cooperação",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "C04",
    "sectionCode": "III.4",
    "sortOrder": 29,
    "tomeSection": "Tomo III — Políticas Brasileiras",
    "title": "Políticas brasileiras de marinha mercante e construção naval",
    "summary": "Reconstituir políticas para marinha mercante, construção naval, transporte hidroviário, óleo e gás, energias oceânicas e defesa, incluindo planos, ciclos, conteúdo local, legislação tributária e BR do Mar.",
    "functionalResponsible": "M3",
    "support": "M2; M1",
    "portalDeliverable": "Linha do tempo normativa; matriz de instrumentos; avaliação de resultados e cenário atual.",
    "dependencies": "Levantamento documental e validação jurídica/regulatória.",
    "keywords": "Brasil; BR do Mar; conteúdo local; políticas marítimas",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "C05",
    "sectionCode": "III.5",
    "sortOrder": 30,
    "tomeSection": "Tomo III — FMM",
    "title": "Fundo da Marinha Mercante, AFRMM e financiamento",
    "summary": "Avaliar histórico, regulamentação, arrecadação, distribuição, aplicação, projetos financiados, custo de capital, contas vinculadas, riscos, garantias, efeitos distributivos e impacto regional do FMM.",
    "functionalResponsible": "M3",
    "support": "M2; M1",
    "portalDeliverable": "Painel financeiro; fluxos do FMM/AFRMM; simulações representativas; análise de eficiência e eficácia.",
    "dependencies": "Acesso a séries financeiras e definição das premissas para simulações.",
    "keywords": "FMM; AFRMM; financiamento; custo de capital",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "C06",
    "sectionCode": "III.6",
    "sortOrder": 31,
    "tomeSection": "Tomo III — Setores Críticos",
    "title": "Siderurgia, materiais, equipamentos e conteúdo nacional",
    "summary": "Analisar políticas industriais e perfil de nacionalização nos países produtores e no Brasil, destacando siderurgia, materiais, equipamentos navais, fabricantes, capacidade, tecnologia, recursos humanos e cenários prospectivos.",
    "functionalResponsible": "M3",
    "support": "M1; M2",
    "portalDeliverable": "Mapa de fornecedores críticos; fichas de fabricantes; matriz de nacionalização; oportunidades e desafios.",
    "dependencies": "Integração com B07 e com dados empresariais verificáveis.",
    "keywords": "siderurgia; equipamentos navais; fornecedores; nacionalização",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "C07",
    "sectionCode": "III.7",
    "sortOrder": 32,
    "tomeSection": "Tomo III — Ciclos Históricos",
    "title": "Ciclos de expansão e queda da indústria naval brasileira: diagnóstico de sucessos e falhas",
    "summary": "Comparar os ciclos brasileiros de 1970–1980 e 2000–2010 com Coreia do Sul e China, identificando objetivos, instrumentos, resultados, causas endógenas e exógenas, continuidade institucional, demanda, financiamento, produtividade, sucessos, falhas e lições.",
    "functionalResponsible": "M2",
    "support": "M1; M3",
    "portalDeliverable": "Estudo comparativo; matriz de causas; lições de política; síntese visual para o portal.",
    "dependencies": "Compatibilização da narrativa histórica com B02, B03 e C04.",
    "keywords": "ciclos industriais; Coreia; China; lições",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "C08",
    "sectionCode": "III.8",
    "sortOrder": 33,
    "tomeSection": "Tomo III — Cenário Internacional",
    "title": "Fatores geopolíticos e ambientais críticos para a reestruturação da indústria naval brasileira",
    "summary": "Examinar mudanças tecnológicas, ambientais e geopolíticas nos mercados de energia, navegação e defesa, a reorganização de cadeias produtivas, segurança econômica, transição energética, acesso a mercados e tecnologias e suas implicações para a reestruturação da indústria naval brasileira.",
    "functionalResponsible": "M3",
    "support": "M2; M1",
    "portalDeliverable": "Mapa de riscos e oportunidades; cenários externos; nota estratégica.",
    "dependencies": "Definição dos horizontes temporais e variáveis críticas.",
    "keywords": "geopolítica; ambiente; energia; defesa; riscos",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "C09",
    "sectionCode": "III.9",
    "sortOrder": 34,
    "tomeSection": "Tomo III — Ambiente Econômico e Institucional",
    "title": "Ambiente econômico e institucional da indústria marítima brasileira",
    "summary": "Avaliar volume e estabilidade da demanda, condições macroeconômicas, custo de capital, restrições fiscais, câmbio e ambiente de investimento, além da organização, coordenação, capacitação, autonomia e continuidade dos órgãos e agências e dos riscos políticos, econômicos e regulatórios.",
    "functionalResponsible": "M3",
    "support": "M2; M1",
    "portalDeliverable": "Mapa institucional; matriz de riscos; cenários e estratégias; recomendações para o Relatório 2.",
    "dependencies": "Integração das conclusões de todos os tomos e validação pela coordenação geral.",
    "keywords": "instituições; regulação; governança; cenários",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "D01",
    "sectionCode": "IV.1",
    "sortOrder": 35,
    "tomeSection": "Tomo IV — Diagnóstico Integrado",
    "title": "Diagnóstico integrado da competitividade da indústria naval brasileira",
    "summary": "Consolidar os resultados dos Tomos I, II e III, articulando mercados e demanda, capacidade produtiva, tecnologia, produtividade, competitividade, cadeia de suprimentos, políticas públicas, ambiente institucional, financiamento, transição energética e variáveis críticas para os cenários.",
    "functionalResponsible": "M2",
    "support": "M1; M3",
    "portalDeliverable": "Painel integrado de cenários; matriz de segmentos prioritários; avaliação de investimentos, modernização e expansão.",
    "dependencies": "Conclusão dos diagnósticos setoriais e definição das premissas comuns.",
    "keywords": "cenários de demanda; integração; investimentos; segmentos",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "D02",
    "sectionCode": "IV.2",
    "sortOrder": 36,
    "tomeSection": "Tomo IV — Cenários",
    "title": "Cenários para a indústria naval brasileira",
    "summary": "Consolidar as projeções de demanda e definir cenários alternativos, hipóteses, horizontes e incertezas, simulando custos, prazos, qualidade, confiabilidade, financiamento, tributação, regras de bandeira, afretamento, conteúdo local, incentivos, tecnologia, recursos humanos e investimentos.",
    "functionalResponsible": "M2",
    "support": "M1; M3",
    "portalDeliverable": "Painel de cenários; matriz de hipóteses e incertezas; projeções por segmento; simulações de capacidade, competitividade e investimento.",
    "dependencies": "Conclusão do diagnóstico integrado D01 e definição das premissas transversais de demanda, capacidade e financiamento.",
    "keywords": "cenários; demanda; competitividade; financiamento; investimentos",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  },
  {
    "code": "D03",
    "sectionCode": "IV.3",
    "sortOrder": 37,
    "tomeSection": "Tomo IV — Conclusões",
    "title": "Conclusões do Relatório 1 e agenda do Relatório 2",
    "summary": "Sintetizar as conclusões do diagnóstico integrado e dos cenários, explicitar evidências, incertezas, hipóteses e lacunas, indicar segmentos estratégicos e questões que orientarão políticas e o Plano de Ação do Relatório 2.",
    "functionalResponsible": "M3",
    "support": "M1; M2",
    "portalDeliverable": "Resumo executivo; conclusões; agenda do Relatório 2; página de encerramento; versão pública para o portal.",
    "dependencies": "Validação final, revisão cruzada, aprovação editorial e definição do que será publicado.",
    "keywords": "conclusões; prioridades; Plano de Ação; Relatório 2",
    "planningStatus": "Planejada",
    "contentType": "Atividade de desenvolvimento + ficha pública",
    "visibility": "Público após aprovação",
    "acceptanceCriteria": "Texto revisado, fontes registradas, responsável confirmado e ficha de portal preenchida.",
    "sourceBase": "Estrutura-Relatorio_1.docx"
  }
] as const;

export type ActivityPlanItem = (typeof ACTIVITY_PLAN_ITEMS)[number];

export const OPERATIONAL_ACTIVITY_ITEMS = [
  {
    code: "P01",
    parentPlanCode: "A00",
    sectionCode: "AP",
    sortOrder: 38,
    title: "Estruturação do Portal e da arquitetura de publicação do Estudo",
    summary: "Definir o mapa de conteúdos, a arquitetura de publicação, os critérios de atualização e os fluxos de validação do Portal Naval previstos na apresentação do Estudo.",
    functionalResponsible: "M3",
    support: "M1; M2",
    portalDeliverable: "Mapa de conteúdos, arquitetura de publicação, critérios de atualização e registro de validação.",
    dependencies: "Desdobramento operacional de A00 e validação da identidade editorial do Estudo.",
    keywords: "Portal Naval; arquitetura de publicação; governança editorial",
    planningStatus: "Planejada",
    contentType: "Atividade complementar de execução",
    visibility: "Interno com publicação após aprovação",
    acceptanceCriteria: "Estrutura de publicação documentada, responsável confirmado e critérios de atualização registrados.",
    sourceBase: "Estrutura-Relatorio_1-V1.docx",
  },
  {
    code: "P02",
    parentPlanCode: "A00",
    sectionCode: "AP",
    sortOrder: 39,
    title: "Organização do banco de dados documental e temático",
    summary: "Organizar a estrutura de dados, os campos de classificação e o registro de fontes que suportam o Portal e o Relatório 1.",
    functionalResponsible: "M3",
    support: "M1; M2",
    portalDeliverable: "Modelo de classificação documental, campos de registro e inventário de fontes.",
    dependencies: "Desdobramento operacional de A00 e definição de metadados para a Biblioteca.",
    keywords: "banco de dados; documentação; fontes; classificação",
    planningStatus: "Planejada",
    contentType: "Atividade complementar de execução",
    visibility: "Interno com publicação após aprovação",
    acceptanceCriteria: "Campos de classificação definidos, fontes registradas e estrutura validada pela coordenação.",
    sourceBase: "Estrutura-Relatorio_1-V1.docx",
  },
  {
    code: "P03",
    parentPlanCode: "A00",
    sectionCode: "AP",
    sortOrder: 40,
    title: "Produção audiovisual do Estudo",
    summary: "Planejar e registrar as peças audiovisuais previstas para comunicação do Estudo, incluindo roteiro, materiais em desenvolvimento e fluxo de aprovação.",
    functionalResponsible: "M3",
    support: "M1; M2",
    portalDeliverable: "Plano audiovisual, roteiro, registro de peças e aprovação editorial.",
    dependencies: "Desdobramento operacional de A00 e definição da arquitetura de publicação P01.",
    keywords: "audiovisual; comunicação; roteiro; publicação",
    planningStatus: "Planejada",
    contentType: "Atividade complementar de execução",
    visibility: "Interno com publicação após aprovação",
    acceptanceCriteria: "Plano e roteiro registrados, materiais vinculados e aprovação editorial definida.",
    sourceBase: "Estrutura-Relatorio_1-V1.docx",
  },
  {
    code: "P04",
    parentPlanCode: "A00",
    sectionCode: "AP",
    sortOrder: 41,
    title: "Elaboração do Sumário Executivo do Relatório 1",
    summary: "Consolidar a síntese executiva do diagnóstico, da metodologia, dos principais resultados e da organização dos Tomos do Relatório 1.",
    functionalResponsible: "M3",
    support: "M1; M2",
    portalDeliverable: "Sumário executivo revisado, com referências e versão apta à publicação.",
    dependencies: "Desdobramento operacional de A00 e consolidação progressiva dos resultados dos Tomos.",
    keywords: "sumário executivo; síntese; Relatório 1",
    planningStatus: "Planejada",
    contentType: "Atividade complementar de execução",
    visibility: "Público após aprovação",
    acceptanceCriteria: "Síntese revisada, fontes registradas, revisão cruzada concluída e aprovação editorial confirmada.",
    sourceBase: "Estrutura-Relatorio_1-V1.docx",
  },
  {
    code: "P05",
    parentPlanCode: "A00",
    sectionCode: "AP",
    sortOrder: 42,
    title: "Delimitação de conteúdo e transição entre os Relatórios 1 e 2",
    summary: "Registrar o conteúdo dos Relatórios 1 e 2, as lacunas que permanecem após o diagnóstico e as questões que serão encaminhadas para o Plano de Ação.",
    functionalResponsible: "M3",
    support: "M1; M2",
    portalDeliverable: "Matriz de escopo, questões de continuidade e agenda de transição para o Relatório 2.",
    dependencies: "Desdobramento operacional de A00 e articulação com D03.",
    keywords: "Relatório 2; escopo; continuidade; Plano de Ação",
    planningStatus: "Planejada",
    contentType: "Atividade complementar de execução",
    visibility: "Interno com publicação após aprovação",
    acceptanceCriteria: "Escopo dos dois relatórios delimitado, lacunas documentadas e agenda de continuidade validada.",
    sourceBase: "Estrutura-Relatorio_1-V1.docx",
  },
  {
    code: "P06",
    parentPlanCode: "C01",
    sectionCode: "III.1",
    sortOrder: 43,
    title: "Desenvolvimento da metodologia de análise de políticas setoriais",
    summary: "Desenvolver o protocolo metodológico para análise comparativa das políticas industrial, marítima e naval no Brasil e no mundo, conforme previsto no Tomo III.",
    functionalResponsible: "M3",
    support: "M2; M1",
    portalDeliverable: "Protocolo metodológico, critérios de comparação e registro de aplicação.",
    dependencies: "Desdobramento operacional de C01 e definição das fontes e períodos relevantes.",
    keywords: "metodologia; política industrial; política marítima; política naval",
    planningStatus: "Planejada",
    contentType: "Atividade complementar de execução",
    visibility: "Interno com publicação após aprovação",
    acceptanceCriteria: "Método documentado, critérios aplicáveis definidos e validação técnica registrada.",
    sourceBase: "Estrutura-Relatorio_1-V1.docx",
  },
  {
    code: "P07",
    parentPlanCode: "B09",
    sectionCode: "II.8",
    sortOrder: 44,
    title: "Metodologia, indicadores e benchmarking de produtividade de estaleiros",
    summary: "Formalizar a metodologia de avaliação tecnológica, os indicadores simplificados de desempenho e o benchmarking de classes de estaleiros previsto para a análise de produtividade e competitividade.",
    functionalResponsible: "M1",
    support: "M2; M3",
    portalDeliverable: "Método de avaliação, painel de indicadores, matriz de benchmarking e critérios de comparação.",
    dependencies: "Desdobramento operacional de B09 e disponibilidade de dados comparáveis de produtividade, capacidade e desempenho.",
    keywords: "produtividade; indicadores; benchmarking; estaleiros",
    planningStatus: "Planejada",
    contentType: "Atividade complementar de execução",
    visibility: "Interno com publicação após aprovação",
    acceptanceCriteria: "Indicadores definidos, método testado e critérios comparativos aprovados pela coordenação.",
    sourceBase: "Estrutura-Relatorio_1-V1.docx",
  },
  {
    code: "P08",
    parentPlanCode: "C05",
    sectionCode: "III.5",
    sortOrder: 45,
    title: "Modelagem e simulações do FMM e das contas vinculadas",
    summary: "Estruturar hipóteses, cenários de simulação e resultados sobre custo efetivo de capital, riscos, garantias, custos financeiros e efeitos distributivos do FMM e das contas vinculadas.",
    functionalResponsible: "M3",
    support: "M2; M1",
    portalDeliverable: "Matriz de hipóteses, simulações representativas e nota técnica de resultados.",
    dependencies: "Desdobramento operacional de C05 e consolidação de dados financeiros e regulatórios relevantes.",
    keywords: "FMM; AFRMM; contas vinculadas; simulação; financiamento",
    planningStatus: "Planejada",
    contentType: "Atividade complementar de execução",
    visibility: "Interno com publicação após aprovação",
    acceptanceCriteria: "Hipóteses registradas, cenários reproduzíveis, resultados revisados e evidências vinculadas.",
    sourceBase: "Estrutura-Relatorio_1-V1.docx",
  },
  {
    code: "P09",
    parentPlanCode: "B02",
    sectionCode: "II.2",
    sortOrder: 46,
    title: "Consolidação das evidências das visitas internacionais",
    summary: "Consolidar roteiros, registros de visitas na China, Coreia do Sul e Índia, fichas de evidência e síntese comparativa das experiências internacionais de desenvolvimento da construção naval.",
    functionalResponsible: "M3",
    support: "M1; M2; consultorias internacionais",
    portalDeliverable: "Roteiros, fichas de evidência, síntese comparativa e vínculos aos registros de Campo e divulgação.",
    dependencies: "Desdobramento operacional de B02 e conclusão dos registros de visitas internacionais.",
    keywords: "visitas internacionais; China; Coreia do Sul; Índia; evidências",
    planningStatus: "Planejada",
    contentType: "Atividade complementar de execução",
    visibility: "Interno com publicação após aprovação",
    acceptanceCriteria: "Registros de visita vinculados, evidências organizadas e síntese comparativa revisada.",
    sourceBase: "Estrutura-Relatorio_1-V1.docx",
  },
  {
    code: "P10",
    parentPlanCode: "B04",
    sectionCode: "II.4",
    sortOrder: 47,
    title: "Consolidação do levantamento de campo dos estaleiros brasileiros",
    summary: "Consolidar fichas de instalações, evidências de campo, cadastro de capacidade e validação do levantamento de estaleiros e instalações brasileiras previsto no Tomo II.",
    functionalResponsible: "M1",
    support: "M2; M3; equipes de campo",
    portalDeliverable: "Fichas de instalações, evidências de campo, cadastro de capacidade e validação do levantamento.",
    dependencies: "Desdobramento operacional de B04 e conclusão das visitas, coleta de fontes primárias e entrevistas estruturadas.",
    keywords: "estaleiros brasileiros; levantamento de campo; capacidade; evidências",
    planningStatus: "Planejada",
    contentType: "Atividade complementar de execução",
    visibility: "Interno com publicação após aprovação",
    acceptanceCriteria: "Fichas consolidadas, evidências vinculadas, campos obrigatórios preenchidos e validação da coordenação registrada.",
    sourceBase: "Estrutura-Relatorio_1-V1.docx",
  },
] as const;

export type OperationalActivityPlanItem = (typeof OPERATIONAL_ACTIVITY_ITEMS)[number];

export function activityPlanItemsForSection(sectionCode: string) {
  return ACTIVITY_PLAN_ITEMS.filter(item => item.sectionCode === sectionCode);
}

export function primaryActivityPlanItem(sectionCode: string) {
  return activityPlanItemsForSection(sectionCode)[0] ?? null;
}
