export const DETAILED_ACTIVITY_ITEMS = [
  { sectionCode: 'AP', detailCode: 'AP.1', detailSortOrder: 1, title: 'Apresentação geral do Estudo.' },
  { sectionCode: 'AP', detailCode: 'AP.2', detailSortOrder: 2, title: 'Descrição do objetivo, metodologia, equipe.' },
  { sectionCode: 'AP', detailCode: 'AP.3', detailSortOrder: 3, title: 'Estrutura do Portal e do Relatório.' },
  { sectionCode: 'AP', detailCode: 'AP.4', detailSortOrder: 4, title: 'Banco de dados.' },
  { sectionCode: 'AP', detailCode: 'AP.5', detailSortOrder: 5, title: 'Audiovisual.' },
  { sectionCode: 'AP', detailCode: 'AP.6', detailSortOrder: 6, title: 'Sumário Executivo.' },
  { sectionCode: 'AP', detailCode: 'AP.7', detailSortOrder: 7, title: 'Conteúdo dos Relatórios 1 e 2.' },
  { sectionCode: 'I.1', detailCode: 'I.1.1', detailSortOrder: 1, title: 'Objetivos do Relatório 1: diagnósticos e cenários.' },
  { sectionCode: 'I.1', detailCode: 'I.1.2', detailSortOrder: 2, title: 'Análise da evolução da indústria naval brasileira, em particular nos períodos 1970-80 e 2000-2010.' },
  { sectionCode: 'I.1', detailCode: 'I.1.3', detailSortOrder: 3, title: 'Sucessos e falhas.' },
  { sectionCode: 'I.1', detailCode: 'I.1.4', detailSortOrder: 4, title: 'Escopo.' },
  { sectionCode: 'I.1', detailCode: 'I.1.5', detailSortOrder: 5, title: 'Construção de navios, embarcações fluviais, offshore, fabricação e integração de módulos, reparo, descomissionamento/desmantelamento.' },
  { sectionCode: 'I.1', detailCode: 'I.1.6', detailSortOrder: 6, title: 'Estrutura do relatório.' },
  { sectionCode: 'I.1', detailCode: 'I.1.7', detailSortOrder: 7, title: 'Os temas são examinados em diferentes capítulos segundo perspectivas complementares.' },
  { sectionCode: 'I.1', detailCode: 'I.1.8', detailSortOrder: 8, title: 'O Tomo I analisa os setores geradores de demanda; o Tomo II, a capacidade de resposta da base produtiva; o Tomo III, as políticas e instituições que condicionam essa resposta; e o Tomo IV integra essas dimensões na construção dos cenários.' },
  { sectionCode: 'I.2', detailCode: 'I.2.1', detailSortOrder: 1, title: 'Economia marítima.' },
  { sectionCode: 'I.2', detailCode: 'I.2.2', detailSortOrder: 2, title: 'Indústria naval, marinha mercante, óleo e gás, geração de energia, pesca, defesa.' },
  { sectionCode: 'I.2', detailCode: 'I.2.3', detailSortOrder: 3, title: 'Interrelação entre os setores.' },
  { sectionCode: 'I.2', detailCode: 'I.2.4', detailSortOrder: 4, title: 'A natureza estratégica da indústria naval e da economia do mar.' },
  { sectionCode: 'I.2', detailCode: 'I.2.5', detailSortOrder: 5, title: 'Aspectos econômicos dos principais segmentos geradores da demanda da indústria naval.' },
  { sectionCode: 'I.2', detailCode: 'I.2.6', detailSortOrder: 6, title: 'Aspectos econômicos, tecnológicos e geopolíticos.' },
  { sectionCode: 'I.2', detailCode: 'I.2.7', detailSortOrder: 7, title: 'Mudanças econômicas, geopolíticas, ambientais, regulatórias e tecnológicas que afetam as indústrias marítimas, e, em particular, a indústria naval.' },
  { sectionCode: 'I.2', detailCode: 'I.2.8', detailSortOrder: 8, title: 'Reorganização das cadeias globais, regionalização produtiva, transição energética.' },
  { sectionCode: 'I.2', detailCode: 'I.2.9', detailSortOrder: 9, title: 'Oportunidades e desafios para a indústria naval brasileira.' },
  { sectionCode: 'I.3', detailCode: 'I.3.1', detailSortOrder: 1, title: 'Estrutura e organização dos mercados de transporte marítimo internacional.' },
  { sectionCode: 'I.3', detailCode: 'I.3.2', detailSortOrder: 2, title: 'Regulação.' },
  { sectionCode: 'I.3', detailCode: 'I.3.3', detailSortOrder: 3, title: 'Comportamento dos principais segmentos do mercado: granéis líquidos, gás, químicos, granéis sólidos e contêineres.' },
  { sectionCode: 'I.3', detailCode: 'I.3.4', detailSortOrder: 4, title: 'Outros segmentos: veículos, cargas de projeto, carga geral, apoio marítimo e portuário.' },
  { sectionCode: 'I.3', detailCode: 'I.3.5', detailSortOrder: 5, title: 'Principais fluxos.' },
  { sectionCode: 'I.3', detailCode: 'I.3.6', detailSortOrder: 6, title: 'Análise dos mercados: tipos de navios, bandeiras, aspectos tecnológicos, fretes, preços, carteiras de encomendas.' },
  { sectionCode: 'I.3', detailCode: 'I.3.7', detailSortOrder: 7, title: 'Navegação e meio ambiente.' },
  { sectionCode: 'I.3', detailCode: 'I.3.8', detailSortOrder: 8, title: 'Evolução e dinâmica recente.' },
  { sectionCode: 'I.3', detailCode: 'I.3.9', detailSortOrder: 9, title: 'Fatores econômicos, geopolíticos e ambientais que condicionam a expansão, renovação e transformação tecnológica das frotas.' },
  { sectionCode: 'I.3', detailCode: 'I.3.10', detailSortOrder: 10, title: 'Tendências.' },
  { sectionCode: 'I.3', detailCode: 'I.3.11', detailSortOrder: 11, title: 'Cenários de demanda para a indústria naval.' },
  { sectionCode: 'I.3', detailCode: 'I.3.12', detailSortOrder: 12, title: 'Desafios e oportunidades para a marinha mercante e a indústria naval no Brasil.' },
  { sectionCode: 'I.4', detailCode: 'I.4.1', detailSortOrder: 1, title: 'Evolução da marinha mercante brasileira.' },
  { sectionCode: 'I.4', detailCode: 'I.4.2', detailSortOrder: 2, title: 'Principais fluxos de transporte marítimo de cabotagem e longo curso.' },
  { sectionCode: 'I.4', detailCode: 'I.4.3', detailSortOrder: 3, title: 'Regulamentação.' },
  { sectionCode: 'I.4', detailCode: 'I.4.4', detailSortOrder: 4, title: 'Organização dos mercados.' },
  { sectionCode: 'I.4', detailCode: 'I.4.5', detailSortOrder: 5, title: 'Gargalos de infraestrutura.' },
  { sectionCode: 'I.4', detailCode: 'I.4.6', detailSortOrder: 6, title: 'Empresas brasileiras de navegação.' },
  { sectionCode: 'I.4', detailCode: 'I.4.7', detailSortOrder: 7, title: 'Frotas.' },
  { sectionCode: 'I.4', detailCode: 'I.4.8', detailSortOrder: 8, title: 'Bandeiras.' },
  { sectionCode: 'I.4', detailCode: 'I.4.9', detailSortOrder: 9, title: 'Afretamento.' },
  { sectionCode: 'I.4', detailCode: 'I.4.10', detailSortOrder: 10, title: 'Integração às redes globais.' },
  { sectionCode: 'I.4', detailCode: 'I.4.11', detailSortOrder: 11, title: 'Apoio portuário.' },
  { sectionCode: 'I.4', detailCode: 'I.4.12', detailSortOrder: 12, title: 'Apoio marítimo (enquadramento como segmento da navegação brasileira).' },
  { sectionCode: 'I.4', detailCode: 'I.4.13', detailSortOrder: 13, title: 'Custos diferenciais da bandeira brasileira.' },
  { sectionCode: 'I.4', detailCode: 'I.4.14', detailSortOrder: 14, title: 'Panorama do setor pesqueiro.' },
  { sectionCode: 'I.4', detailCode: 'I.4.15', detailSortOrder: 15, title: 'Cenários de demanda para construção, reparo, conversão e modernização de navios e embarcações de apoio.' },
  { sectionCode: 'I.5', detailCode: 'I.5.1', detailSortOrder: 1, title: 'Análise das principais bacias.' },
  { sectionCode: 'I.5', detailCode: 'I.5.2', detailSortOrder: 2, title: 'Infraestrutura.' },
  { sectionCode: 'I.5', detailCode: 'I.5.3', detailSortOrder: 3, title: 'Principais fluxos de carga.' },
  { sectionCode: 'I.5', detailCode: 'I.5.4', detailSortOrder: 4, title: 'Estrutura e organização dos mercados: empresas, frotas.' },
  { sectionCode: 'I.5', detailCode: 'I.5.5', detailSortOrder: 5, title: 'Transporte multimodal.' },
  { sectionCode: 'I.5', detailCode: 'I.5.6', detailSortOrder: 6, title: 'Navegação fluvial de percurso internacional.' },
  { sectionCode: 'I.5', detailCode: 'I.5.7', detailSortOrder: 7, title: 'Impactos ambientais.' },
  { sectionCode: 'I.5', detailCode: 'I.5.8', detailSortOrder: 8, title: 'Transporte de passageiros na Região Amazônica.' },
  { sectionCode: 'I.5', detailCode: 'I.5.9', detailSortOrder: 9, title: 'Transporte hidroviário urbano.' },
  { sectionCode: 'I.5', detailCode: 'I.5.10', detailSortOrder: 10, title: 'Navegação e desenvolvimento regional.' },
  { sectionCode: 'I.5', detailCode: 'I.5.11', detailSortOrder: 11, title: 'Cenários de demanda para construção de embarcações fluviais.' },
  { sectionCode: 'I.6', detailCode: 'I.6.1', detailSortOrder: 1, title: 'Evolução e perspectivas da indústria de óleo e gás offshore.' },
  { sectionCode: 'I.6', detailCode: 'I.6.2', detailSortOrder: 2, title: 'Regiões de produção.' },
  { sectionCode: 'I.6', detailCode: 'I.6.3', detailSortOrder: 3, title: 'Principais empresas e países.' },
  { sectionCode: 'I.6', detailCode: 'I.6.4', detailSortOrder: 4, title: 'Marcos regulatórios nos principais polos.' },
  { sectionCode: 'I.6', detailCode: 'I.6.5', detailSortOrder: 5, title: 'Tipos de unidades flutuantes de exploração e produção.' },
  { sectionCode: 'I.6', detailCode: 'I.6.6', detailSortOrder: 6, title: 'Análise dos sistemas de operação em função das características físicas e logísticas dos campos.' },
  { sectionCode: 'I.6', detailCode: 'I.6.7', detailSortOrder: 7, title: 'Comportamento dos mercados de óleo e gás e interrelação com o mercado de unidades de E&P, em particular, FPSO e Sondas.' },
  { sectionCode: 'I.6', detailCode: 'I.6.8', detailSortOrder: 8, title: 'Análise dos mercados de construção e afretamento.' },
  { sectionCode: 'I.6', detailCode: 'I.6.9', detailSortOrder: 9, title: 'Tendências e cenários globais de demanda: construção, fabricação e integração de módulos, conversão, descomissionamento' },
  { sectionCode: 'I.6', detailCode: 'I.6.10', detailSortOrder: 10, title: 'Atividade offshore no Brasil.' },
  { sectionCode: 'I.6', detailCode: 'I.6.11', detailSortOrder: 11, title: 'Principais campos.' },
  { sectionCode: 'I.6', detailCode: 'I.6.12', detailSortOrder: 12, title: 'Empresas e participação no mercado.' },
  { sectionCode: 'I.6', detailCode: 'I.6.13', detailSortOrder: 13, title: 'Tipo de unidades em operação e perspectivas.' },
  { sectionCode: 'I.6', detailCode: 'I.6.14', detailSortOrder: 14, title: 'Descomissionamento.' },
  { sectionCode: 'I.6', detailCode: 'I.6.15', detailSortOrder: 15, title: 'Cenários de demanda: construção, fabricação e integração de módulos, conversão, descomissionamento.' },
  { sectionCode: 'I.6', detailCode: 'I.6.16', detailSortOrder: 16, title: 'Mercado mundial de navios aliviadores e embarcações de apoio offshore.' },
  { sectionCode: 'I.6', detailCode: 'I.6.17', detailSortOrder: 17, title: 'Tipos de embarcações e padrões de operação.' },
  { sectionCode: 'I.6', detailCode: 'I.6.18', detailSortOrder: 18, title: 'Participação do Brasil no mercado mundial.' },
  { sectionCode: 'I.6', detailCode: 'I.6.19', detailSortOrder: 19, title: 'Estrutura do mercado brasileiro.' },
  { sectionCode: 'I.6', detailCode: 'I.6.20', detailSortOrder: 20, title: 'Comparação do mercado brasileiro com as principais regiões: modos de operação, tipos de afretamento, preços.' },
  { sectionCode: 'I.6', detailCode: 'I.6.21', detailSortOrder: 21, title: 'regulamentação.' },
  { sectionCode: 'I.6', detailCode: 'I.6.22', detailSortOrder: 22, title: 'Empresas, frotas, verticalização.' },
  { sectionCode: 'I.6', detailCode: 'I.6.23', detailSortOrder: 23, title: 'Cenários de demanda por aliviadores e OSV no Brasil.' },
  { sectionCode: 'I.6', detailCode: 'I.6.24', detailSortOrder: 24, title: 'O setor de geração eólica no Brasil.' },
  { sectionCode: 'I.6', detailCode: 'I.6.25', detailSortOrder: 25, title: 'Tipos de instalações e embarcações de apoio.' },
  { sectionCode: 'I.6', detailCode: 'I.6.26', detailSortOrder: 26, title: 'Evolução e perspectivas.' },
  { sectionCode: 'I.6', detailCode: 'I.6.27', detailSortOrder: 27, title: 'Cenários de demanda por embarcações de apoio especializadas e construção de instalações de geração eólica offshore.' },
  { sectionCode: 'I.7', detailCode: 'I.7.1', detailSortOrder: 1, title: 'Evolução e perspectivas dos programas de construção naval militar no Brasil.' },
  { sectionCode: 'I.7', detailCode: 'I.7.2', detailSortOrder: 2, title: 'Experiências internacionais relevantes de desenvolvimento da indústria naval militar.' },
  { sectionCode: 'I.7', detailCode: 'I.7.3', detailSortOrder: 3, title: 'Programas de offset, conteúdo local, clusters produtivos e estratégias de capacitação tecnológica e inovação.' },
  { sectionCode: 'I.7', detailCode: 'I.7.4', detailSortOrder: 4, title: 'Cenários de demanda por navios e embarcações militares.' },
  { sectionCode: 'I.8', detailCode: 'I.8.1', detailSortOrder: 1, title: 'Análise do processo de descarbonização da indústria marítima mundial, com foco nas metas da IMO e nas principais estratégias nacionais e regionais.' },
  { sectionCode: 'I.8', detailCode: 'I.8.2', detailSortOrder: 2, title: 'Respostas de armadores, operadores, portos e fornecedores de energia.' },
  { sectionCode: 'I.8', detailCode: 'I.8.3', detailSortOrder: 3, title: 'Identificação e classificação das tecnologias emergentes voltadas à descarbonização e à melhoria da eficiência energética de embarcações e unidades offshore, abrangendo soluções de projeto, propulsão, operação e digitalização.' },
  { sectionCode: 'I.8', detailCode: 'I.8.4', detailSortOrder: 4, title: 'Infraestrutura de abastecimento.' },
  { sectionCode: 'I.8', detailCode: 'I.8.5', detailSortOrder: 5, title: 'Análise do estado atual da frota global e brasileira em relação ao uso de combustíveis alternativos e de tecnologias de eficiência energética.' },
  { sectionCode: 'I.8', detailCode: 'I.8.6', detailSortOrder: 6, title: 'Análise do efeito da transição energética sobre mercados, frotas e demanda por embarcações novas e retrofitting.' },
  { sectionCode: 'I.8', detailCode: 'I.8.7', detailSortOrder: 7, title: 'Análise do potencial competitivo do Brasil na produção e uso de combustíveis renováveis para o transporte marítimo e identificação das necessidades de infraestrutura portuária e logística verde.' },
  { sectionCode: 'II.1', detailCode: 'II.1.1', detailSortOrder: 1, title: 'Análise da trajetória e da estrutura atual da construção naval mundial.' },
  { sectionCode: 'II.1', detailCode: 'II.1.2', detailSortOrder: 2, title: 'Evolução da produção, capacidade de estaleiros, padrão tecnológico.' },
  { sectionCode: 'II.1', detailCode: 'II.1.3', detailSortOrder: 3, title: 'Capacidade instalada, por país e por classe de estaleiro/segmento do mercado.' },
  { sectionCode: 'II.1', detailCode: 'II.1.4', detailSortOrder: 4, title: 'Principais grupos empresariais e principais estaleiros.' },
  { sectionCode: 'II.1', detailCode: 'II.1.5', detailSortOrder: 5, title: 'Especialização e seriação.' },
  { sectionCode: 'II.1', detailCode: 'II.1.6', detailSortOrder: 6, title: 'Segmentos de navios, apoio marítimo, offshore e defesa.' },
  { sectionCode: 'II.1', detailCode: 'II.1.7', detailSortOrder: 7, title: 'Protecionismo.' },
  { sectionCode: 'II.1', detailCode: 'II.1.8', detailSortOrder: 8, title: 'Fatores de competitividade.' },
  { sectionCode: 'II.1', detailCode: 'II.1.9', detailSortOrder: 9, title: 'Tecnologia.' },
  { sectionCode: 'II.1', detailCode: 'II.1.10', detailSortOrder: 10, title: 'Cadeia produtiva.' },
  { sectionCode: 'II.1', detailCode: 'II.1.11', detailSortOrder: 11, title: 'Comportamento dos mercados.' },
  { sectionCode: 'II.1', detailCode: 'II.1.12', detailSortOrder: 12, title: 'Impactos recentes ambientais, tecnológicos, geopolíticos.' },
  { sectionCode: 'II.2', detailCode: 'II.2.1', detailSortOrder: 1, title: 'Estudos dos casos de China, Coreia do Sul, Japão, Singapura, Estados Unidos, países europeus e produtores emergentes, incluindo Índia, Vietnã e Indonésia.' },
  { sectionCode: 'II.2', detailCode: 'II.2.2', detailSortOrder: 2, title: 'Protecionismo.' },
  { sectionCode: 'II.2', detailCode: 'II.2.3', detailSortOrder: 3, title: 'Evolução da indústria, estrutura empresarial, especialização, qualificação tecnológica, recursos humanos, cadeia de fornecedores, inserção internacional.' },
  { sectionCode: 'II.2', detailCode: 'II.2.4', detailSortOrder: 4, title: 'Evolução da produtividade.' },
  { sectionCode: 'II.2', detailCode: 'II.2.5', detailSortOrder: 5, title: 'Competitividade.' },
  { sectionCode: 'II.2', detailCode: 'II.2.6', detailSortOrder: 6, title: 'Resultados produtivos.' },
  { sectionCode: 'II.2', detailCode: 'II.2.7', detailSortOrder: 7, title: 'Estratégias de desenvolvimento tecnológico – catching up.' },
  { sectionCode: 'II.2', detailCode: 'II.2.8', detailSortOrder: 8, title: 'O trabalho inclui visitas a estaleiros e organizações relevantes na China, Coreia e Índia.' },
  { sectionCode: 'II.3', detailCode: 'II.3.1', detailSortOrder: 1, title: 'Histórico.' },
  { sectionCode: 'II.3', detailCode: 'II.3.2', detailSortOrder: 2, title: 'Evolução da indústria naval moderna brasileira.' },
  { sectionCode: 'II.3', detailCode: 'II.3.3', detailSortOrder: 3, title: 'Planos e Programas de desenvolvimento.' },
  { sectionCode: 'II.3', detailCode: 'II.3.4', detailSortOrder: 4, title: 'Os ciclos de 1970-1980 e 2000-2010: expansão da capacidade e retração subsequente.' },
  { sectionCode: 'II.3', detailCode: 'II.3.5', detailSortOrder: 5, title: 'Construção de unidades offshore.' },
  { sectionCode: 'II.3', detailCode: 'II.3.6', detailSortOrder: 6, title: 'Construção militar.' },
  { sectionCode: 'II.3', detailCode: 'II.3.7', detailSortOrder: 7, title: 'Embarcações fluviais.' },
  { sectionCode: 'II.3', detailCode: 'II.3.8', detailSortOrder: 8, title: 'Evolução da estrutura da indústria: trajetória das empresas, da capacidade produtiva e da cadeia de fornecedores.' },
  { sectionCode: 'II.3', detailCode: 'II.3.9', detailSortOrder: 9, title: 'Desempenho.' },
  { sectionCode: 'II.3', detailCode: 'II.3.10', detailSortOrder: 10, title: 'Qualificação tecnológica e recursos humanos.' },
  { sectionCode: 'II.3', detailCode: 'II.3.11', detailSortOrder: 11, title: 'Contratos e produção realizada.' },
  { sectionCode: 'II.3', detailCode: 'II.3.12', detailSortOrder: 12, title: 'Preços e prazos.' },
  { sectionCode: 'II.3', detailCode: 'II.3.13', detailSortOrder: 13, title: 'Distribuição geográfica.' },
  { sectionCode: 'II.3', detailCode: 'II.3.14', detailSortOrder: 14, title: 'Fatores econômicos, empresariais, tecnológicos, regulatórios e institucionais que determinaram os resultados alcançados.' },
  { sectionCode: 'II.4', detailCode: 'II.4.1', detailSortOrder: 1, title: 'Diagnóstico abrangente da indústria naval brasileira, avaliando infraestrutura, capacidade produtiva, níveis de produtividade, capacitação tecnológica, cadeia de suprimentos e potencial de modernização dos estaleiros nacionais.' },
  { sectionCode: 'II.4', detailCode: 'II.4.2', detailSortOrder: 2, title: 'Levantamento de todos os estaleiros e instalações de fabricação e integração de módulos relevantes, em operação ou não.' },
  { sectionCode: 'II.4', detailCode: 'II.4.3', detailSortOrder: 3, title: 'Análise da evolução das instalações, organização corporativa, capacidade, produção e desempenho.' },
  { sectionCode: 'II.4', detailCode: 'II.4.4', detailSortOrder: 4, title: 'Estrutura e situação atuais.' },
  { sectionCode: 'II.4', detailCode: 'II.4.5', detailSortOrder: 5, title: 'Carteiras, engenharia de projeto e de processos, infraestrutura industrial, processos, modelo de organização e gestão.' },
  { sectionCode: 'II.4', detailCode: 'II.4.6', detailSortOrder: 6, title: 'Cadeia produtiva, por tipo de produto e região.' },
  { sectionCode: 'II.4', detailCode: 'II.4.7', detailSortOrder: 7, title: 'Análise do potencial de reativação ou adaptação para operação sustentável e competitiva, para os segmentos de maior viabilidade.' },
  { sectionCode: 'II.4', detailCode: 'II.4.8', detailSortOrder: 8, title: 'Serão considerados os estaleiros dedicados à construção de navios convencionais, embarcações fluviais, embarcações de apoio offshore, plataformas offshore e módulos de plantas de processo bem como os estaleiros de reparo, conversão e desmonte de plataformas e navios.' },
  { sectionCode: 'II.4', detailCode: 'II.4.9', detailSortOrder: 9, title: 'O trabalho inclui visitas às instalações para levantamento de campo.' },
  { sectionCode: 'II.5', detailCode: 'II.5.1', detailSortOrder: 1, title: 'Situação atual e tendências do mercado mundial.' },
  { sectionCode: 'II.5', detailCode: 'II.5.2', detailSortOrder: 2, title: 'Regulação internacional e nacional.' },
  { sectionCode: 'II.5', detailCode: 'II.5.3', detailSortOrder: 3, title: 'Análise comparativa entre estaleiros de reparo e construção e instalações de descomissionamento.' },
  { sectionCode: 'II.5', detailCode: 'II.5.4', detailSortOrder: 4, title: 'Diagnóstico da demanda, da infraestrutura, das empresas e da capacidade nacional para reparo, docagem, conversão e modernização de embarcações e unidades offshore, considerando a competição internacional.' },
  { sectionCode: 'II.5', detailCode: 'II.5.5', detailSortOrder: 5, title: 'Desafios e oportunidades em reparo, conversão, retrofitting e desmantelamento.' },
  { sectionCode: 'II.6', detailCode: 'II.6.1', detailSortOrder: 1, title: 'Perfil de nacionalização de componentes na indústria de construção naval nos principais países produtores.' },
  { sectionCode: 'II.6', detailCode: 'II.6.2', detailSortOrder: 2, title: 'Importância das indústrias siderúrgica e de materiais, equipamentos e sistemas navais para a indústria de construção naval dos países selecionados.' },
  { sectionCode: 'II.6', detailCode: 'II.6.3', detailSortOrder: 3, title: 'Evolução do índice de nacionalização nas diferentes fases da indústria naval brasileira.' },
  { sectionCode: 'II.6', detailCode: 'II.6.4', detailSortOrder: 4, title: 'Levantamento e análise da cadeia de suprimentos no cenário atual, para as principais classes de estaleiros, regiões e tipos de produtos.' },
  { sectionCode: 'II.6', detailCode: 'II.6.5', detailSortOrder: 5, title: 'Serão examinadas localização, capacidade, conteúdo nacional, dependências externas, lacunas produtivas e tecnológicas, relações entre estaleiros e fornecedores e diferenças entre as cadeias civil, fluvial, offshore e militar.' },
  { sectionCode: 'II.7', detailCode: 'II.7.1', detailSortOrder: 1, title: 'Análise da capacitação dos estaleiros brasileiros em engenharia de produtos e de processos e de gestão da produção.' },
  { sectionCode: 'II.7', detailCode: 'II.7.2', detailSortOrder: 2, title: 'Perfil da força de trabalho empregada nos estaleiros , nos níveis básico, técnico e gerencial.' },
  { sectionCode: 'II.7', detailCode: 'II.7.3', detailSortOrder: 3, title: 'Análise das capacidades de pesquisa, desenvolvimento e inovação disponíveis em empresas, universidades e centros de pesquisa nas áreas relevantes para a indústria naval.' },
  { sectionCode: 'II.7', detailCode: 'II.7.4', detailSortOrder: 4, title: 'Avaliação das relações entre essas instituições e a base produtiva.' },
  { sectionCode: 'II.7', detailCode: 'II.7.5', detailSortOrder: 5, title: 'Análise da disponibilidade de força de trabalho no Brasil nos níveis operacional, técnico, de engenharia e gerencial, bem como dos sistemas de formação e qualificação de recursos humanos nos níveis básico, técnico e superior.' },
  { sectionCode: 'II.8', detailCode: 'II.8.1', detailSortOrder: 1, title: 'Metodologia para avaliação tecnológica de estaleiros.' },
  { sectionCode: 'II.8', detailCode: 'II.8.2', detailSortOrder: 2, title: 'Proposição de indicadores simplificados para avaliação de desempenho e benchmarking.' },
  { sectionCode: 'II.8', detailCode: 'II.8.3', detailSortOrder: 3, title: 'Análise dos padrões tecnológicos, produtividade e desempenho para as principais classes de estaleiros mundiais, em função da capacidade produtiva, especialização e seriação.' },
  { sectionCode: 'II.8', detailCode: 'II.8.4', detailSortOrder: 4, title: 'Análise dos padrões tecnológicos, produtividade e desempenho dos estaleiros brasileiros, em comparação com as classes relevantes.' },
  { sectionCode: 'II.8', detailCode: 'II.8.5', detailSortOrder: 5, title: 'Serão considerados os últimos períodos de operação contínua, a situação atual e o potencial de cada estaleiro.' },
  { sectionCode: 'II.8', detailCode: 'II.8.6', detailSortOrder: 6, title: 'Análise das possibilidades de inserção competitiva de cada estaleiro, com identificação de potencialidades, limitações e gargalos e proposição de metas de produtividade e desempenho.' },
  { sectionCode: 'II.9', detailCode: 'II.9.1', detailSortOrder: 1, title: 'Síntese das mudanças de mercado e das tendências tecnológicas associadas à descarbonização, analisadas no Tomo I, e impactos sobre o projeto, construção, conversão e reparo de embarcações e unidades offshore.' },
  { sectionCode: 'II.9', detailCode: 'II.9.2', detailSortOrder: 2, title: 'Análise das competências requeridas para projeto e construção de navios capazes ou preparados para utilização de novos combustíveis, e para desenvolvimento e aplicação de sistemas de eficiência energética, captura de carbono e tecnologias correlatas.' },
  { sectionCode: 'II.9', detailCode: 'II.9.3', detailSortOrder: 3, title: 'Avaliação das capacidades e deficiências da indústria naval brasileira para inserção competitiva nesses mercados.' },
  { sectionCode: 'II.9', detailCode: 'II.9.4', detailSortOrder: 4, title: 'Análise da descarbonização dos próprios processos de construção naval.' },
  { sectionCode: 'II.9', detailCode: 'II.9.5', detailSortOrder: 5, title: 'Identificação dos desafios e das oportunidades para estaleiros, empresas de engenharia e fornecedores brasileiros.' },
  { sectionCode: 'III.1', detailCode: 'III.1.1', detailSortOrder: 1, title: 'Política industrial: Revisão da literatura, conceitos teóricos e justificativas econômicas.' },
  { sectionCode: 'III.1', detailCode: 'III.1.2', detailSortOrder: 2, title: 'Políticas horizontais e setoriais.' },
  { sectionCode: 'III.1', detailCode: 'III.1.3', detailSortOrder: 3, title: 'Transformações ambientais e geopolíticas em curso e tendências.' },
  { sectionCode: 'III.1', detailCode: 'III.1.4', detailSortOrder: 4, title: 'O papel das organizações multilaterais.' },
  { sectionCode: 'III.1', detailCode: 'III.1.5', detailSortOrder: 5, title: 'Evolução das políticas industriais praticadas no Brasil.' },
  { sectionCode: 'III.1', detailCode: 'III.1.6', detailSortOrder: 6, title: 'Políticas marítimas e políticas de construção naval.' },
  { sectionCode: 'III.1', detailCode: 'III.1.7', detailSortOrder: 7, title: 'Justificativas econômicas, estratégicas e geopolíticas.' },
  { sectionCode: 'III.1', detailCode: 'III.1.8', detailSortOrder: 8, title: 'Cenário atual e tendências.' },
  { sectionCode: 'III.1', detailCode: 'III.1.9', detailSortOrder: 9, title: 'Desenvolvimento de metodologia de análise da evolução das políticas setoriais voltadas para a indústria naval aplicadas no Brasil e no mundo nos períodos relevantes.' },
  { sectionCode: 'III.1', detailCode: 'III.1.10', detailSortOrder: 10, title: 'Relevância de instrumentos horizontais existentes para impulsionar a indústria naval, como os propostos na Nova Indústria Brasil (NIB) e em outras políticas.' },
  { sectionCode: 'III.1', detailCode: 'III.1.11', detailSortOrder: 11, title: 'Políticas públicas e mecanismos de fomento à descarbonização marítima.' },
  { sectionCode: 'III.1', detailCode: 'III.1.12', detailSortOrder: 12, title: 'Avaliação de sua aplicabilidade ao contexto brasileiro.' },
  { sectionCode: 'III.1', detailCode: 'III.1.13', detailSortOrder: 13, title: 'Desafios regulatórios nacionais e internacionais para a introdução de novos combustíveis marítimos.' },
  { sectionCode: 'III.1', detailCode: 'III.1.14', detailSortOrder: 14, title: 'Possibilidades para o Brasil na transição energética marítima global.' },
  { sectionCode: 'III.2', detailCode: 'III.2.1', detailSortOrder: 1, title: 'Justificativas econômicas, estratégicas e geopolíticas para políticas setoriais de marinha mercante – evolução desde o pós-guerra.' },
  { sectionCode: 'III.2', detailCode: 'III.2.2', detailSortOrder: 2, title: 'Histórico (modelos e instrumentos de proteção e incentivo) nos principais países marítimos.' },
  { sectionCode: 'III.2', detailCode: 'III.2.3', detailSortOrder: 3, title: 'Regulação nacional e internacional e acordos bilaterais e multilaterais.' },
  { sectionCode: 'III.2', detailCode: 'III.2.4', detailSortOrder: 4, title: 'Análise de casos relevantes: Europa Ocidental, China, Coreia, Japão, EUA, Austrália, Nova Zelândia, Singapura, Europa Oriental, Turquia, Índia, com foco nas últimas décadas.' },
  { sectionCode: 'III.2', detailCode: 'III.2.5', detailSortOrder: 5, title: 'Análise dos principais mecanismos de proteção e incentivo: registros alternativos, financiamento e outros instrumentos financeiros, subsídios, incentivos fiscais, reserva de mercado e de carga, preferência de bandeira, políticas de tripulação e de desenvolvimento tecnológico.' },
  { sectionCode: 'III.2', detailCode: 'III.2.6', detailSortOrder: 6, title: 'Identificação dos casos mais expressivos de sucesso e falha e dos resultados sobre frota, participação no mercado e competitividade.' },
  { sectionCode: 'III.3', detailCode: 'III.3.1', detailSortOrder: 1, title: 'Inter-relação entre políticas de construção naval e de transporte marítimo.' },
  { sectionCode: 'III.3', detailCode: 'III.3.2', detailSortOrder: 2, title: 'Justificativas econômicas, estratégicas e geopolíticas para políticas setoriais de construção naval – evolução desde o pós-guerra.' },
  { sectionCode: 'III.3', detailCode: 'III.3.3', detailSortOrder: 3, title: 'Regulamentação nacional e internacional.' },
  { sectionCode: 'III.3', detailCode: 'III.3.4', detailSortOrder: 4, title: 'Organismos internacionais e acordos bilaterais e multilaterais.' },
  { sectionCode: 'III.3', detailCode: 'III.3.5', detailSortOrder: 5, title: 'Histórico nos principais países produtores, principais ciclos de industrialização e processos de realocação geográfica.' },
  { sectionCode: 'III.3', detailCode: 'III.3.6', detailSortOrder: 6, title: 'Impacto das políticas setoriais e horizontais na consolidação das indústrias nacionais e na distribuição geográfica da produção.' },
  { sectionCode: 'III.3', detailCode: 'III.3.7', detailSortOrder: 7, title: 'Análise de casos relevantes: Europa, EUA, Japão, Coreia, China, Singapura, Europa Oriental, Turquia, Índia, Indonésia e Vietnã.' },
  { sectionCode: 'III.3', detailCode: 'III.3.8', detailSortOrder: 8, title: 'Síntese dos resultados das políticas, com base na evolução das indústrias nacionais analisada no Tomo II.' },
  { sectionCode: 'III.3', detailCode: 'III.3.9', detailSortOrder: 9, title: 'Mecanismos de proteção e incentivo: planejamento governamental, estatização, restrições de mercado, subsídios, incentivos fiscais, instrumentos financeiros, garantias e créditos para exportação e compras governamentais.' },
  { sectionCode: 'III.3', detailCode: 'III.3.10', detailSortOrder: 10, title: 'Cooperação internacional.' },
  { sectionCode: 'III.3', detailCode: 'III.3.11', detailSortOrder: 11, title: 'Integração das estratégias de catching-up tecnológico nas políticas do Japão, da Coreia e da China.' },
  { sectionCode: 'III.3', detailCode: 'III.3.12', detailSortOrder: 12, title: 'Impactos das transformações em curso e tendências.' },
  { sectionCode: 'III.4', detailCode: 'III.4.1', detailSortOrder: 1, title: 'Evolução das políticas marítimas no Brasil – marinha mercante, construção naval, navegação interior, óleo e gás offshore, energias oceânicas e defesa.' },
  { sectionCode: 'III.4', detailCode: 'III.4.2', detailSortOrder: 2, title: 'Inter-relações entre as políticas dos diferentes setores.' },
  { sectionCode: 'III.4', detailCode: 'III.4.3', detailSortOrder: 3, title: 'Os Planos de Desenvolvimento e os Planos de Construção Naval.' },
  { sectionCode: 'III.4', detailCode: 'III.4.4', detailSortOrder: 4, title: 'Os ciclos de expansão e queda de 1970-1980 e 2000-2010.' },
  { sectionCode: 'III.4', detailCode: 'III.4.5', detailSortOrder: 5, title: 'Principais mecanismos de intervenção: reserva de mercado e de carga, preferência de bandeira, políticas de tripulação, financiamento, incentivos fiscais, conteúdo local e compras governamentais.' },
  { sectionCode: 'III.4', detailCode: 'III.4.6', detailSortOrder: 6, title: 'O FMM como principal instrumento de financiamento (analisado detalhadamente no Capítulo 5).' },
  { sectionCode: 'III.4', detailCode: 'III.4.7', detailSortOrder: 7, title: 'Síntese dos resultados alcançados, deixando a análise de sucessos e falhas para o Capítulo 7.' },
  { sectionCode: 'III.4', detailCode: 'III.4.8', detailSortOrder: 8, title: 'Políticas para os setores de óleo e gás, defesa e energia e seus impactos sobre a indústria naval.' },
  { sectionCode: 'III.4', detailCode: 'III.4.9', detailSortOrder: 9, title: 'Cenário atual: Lei nº 14.301/2022 (BR do Mar), conteúdo local, legislação tributária e demais instrumentos em vigor.' },
  { sectionCode: 'III.5', detailCode: 'III.5.1', detailSortOrder: 1, title: 'Histórico e relevância para a indústria marítima brasileira.' },
  { sectionCode: 'III.5', detailCode: 'III.5.2', detailSortOrder: 2, title: 'Evolução da regulamentação do AFRMM e do FMM.' },
  { sectionCode: 'III.5', detailCode: 'III.5.3', detailSortOrder: 3, title: 'Estrutura institucional, agentes financeiros e processo de aprovação e concessão dos financiamentos.' },
  { sectionCode: 'III.5', detailCode: 'III.5.4', detailSortOrder: 4, title: 'Evolução da arrecadação, distribuição e aplicação dos recursos.' },
  { sectionCode: 'III.5', detailCode: 'III.5.5', detailSortOrder: 5, title: 'Eficiência dos projetos financiados (obras concluídas, custos e prazos).' },
  { sectionCode: 'III.5', detailCode: 'III.5.6', detailSortOrder: 6, title: 'Eficácia do sistema (consolidação de empresas e evolução da competitividade).' },
  { sectionCode: 'III.5', detailCode: 'III.5.7', detailSortOrder: 7, title: 'Análise do efeito do financiamento e do emprego das contas vinculadas sobre o custo efetivo de capital.' },
  { sectionCode: 'III.5', detailCode: 'III.5.8', detailSortOrder: 8, title: 'Simulação para situações representativas e relevantes.' },
  { sectionCode: 'III.5', detailCode: 'III.5.9', detailSortOrder: 9, title: 'Riscos, garantias e custos financeiros.' },
  { sectionCode: 'III.5', detailCode: 'III.5.10', detailSortOrder: 10, title: 'Alocação de custos e benefícios.' },
  { sectionCode: 'III.5', detailCode: 'III.5.11', detailSortOrder: 11, title: 'Efeitos distributivos intersetoriais e inter-regionais.' },
  { sectionCode: 'III.5', detailCode: 'III.5.12', detailSortOrder: 12, title: 'Impacto sobre a navegação interior e o desenvolvimento regional.' },
  { sectionCode: 'III.5', detailCode: 'III.5.13', detailSortOrder: 13, title: 'Análise da racionalidade econômica e estratégica do sistema.' },
  { sectionCode: 'III.5', detailCode: 'III.5.14', detailSortOrder: 14, title: 'Alterações introduzidas pela Lei nº 14.301/2022 (BR do Mar) e avaliação do modelo atual.' },
  { sectionCode: 'III.6', detailCode: 'III.6.1', detailSortOrder: 1, title: 'Políticas industriais e perfil de nacionalização de componentes na indústria de construção naval nos principais países produtores.' },
  { sectionCode: 'III.6', detailCode: 'III.6.2', detailSortOrder: 2, title: 'Políticas de conteúdo local como instrumento de política industrial.' },
  { sectionCode: 'III.6', detailCode: 'III.6.3', detailSortOrder: 3, title: 'Efeito sobre os índices de nacionalização e sobre o desempenho da indústria naval.' },
  { sectionCode: 'III.6', detailCode: 'III.6.4', detailSortOrder: 4, title: 'Importância da indústria siderúrgica e da indústria de materiais e equipamentos navais para a indústria de construção naval dos países relevantes.' },
  { sectionCode: 'III.6', detailCode: 'III.6.5', detailSortOrder: 5, title: 'Políticas industriais voltadas para esses setores e sua articulação com as políticas de construção naval.' },
  { sectionCode: 'III.6', detailCode: 'III.6.6', detailSortOrder: 6, title: 'Histórico e estrutura da indústria siderúrgica e da indústria de materiais e equipamentos navais no Brasil.' },
  { sectionCode: 'III.6', detailCode: 'III.6.7', detailSortOrder: 7, title: 'Principais empresas, localização, capacidade produtiva, tecnologia, recursos humanos e dependência de importações.' },
  { sectionCode: 'III.6', detailCode: 'III.6.8', detailSortOrder: 8, title: 'Políticas industriais adotadas e evolução dos índices de nacionalização nas diferentes fases.' },
  { sectionCode: 'III.6', detailCode: 'III.6.9', detailSortOrder: 9, title: 'Cenários prospectivos.' },
  { sectionCode: 'III.6', detailCode: 'III.6.10', detailSortOrder: 10, title: 'Oportunidades e desafios para o desenvolvimento da cadeia nacional de suprimentos.' },
  { sectionCode: 'III.6', detailCode: 'III.6.11', detailSortOrder: 11, title: 'Importância para o desenvolvimento competitivo da indústria naval.' },
  { sectionCode: 'III.7', detailCode: 'III.7.1', detailSortOrder: 1, title: 'O ciclo de expansão das décadas de 1970 e 1980 no Brasil.' },
  { sectionCode: 'III.7', detailCode: 'III.7.2', detailSortOrder: 2, title: 'Objetivos, instrumentos e resultados das políticas adotadas.' },
  { sectionCode: 'III.7', detailCode: 'III.7.3', detailSortOrder: 3, title: 'Fatores endógenos e exógenos da crise e da retração.' },
  { sectionCode: 'III.7', detailCode: 'III.7.4', detailSortOrder: 4, title: 'Comparação com a trajetória da Coreia do Sul no mesmo período.' },
  { sectionCode: 'III.7', detailCode: 'III.7.5', detailSortOrder: 5, title: 'O ciclo de expansão das décadas de 2000 e 2010.' },
  { sectionCode: 'III.7', detailCode: 'III.7.6', detailSortOrder: 6, title: 'Objetivos, instrumentos e resultados das políticas adotadas.' },
  { sectionCode: 'III.7', detailCode: 'III.7.7', detailSortOrder: 7, title: 'Fatores que determinaram a expansão e a posterior queda da atividade.' },
  { sectionCode: 'III.7', detailCode: 'III.7.8', detailSortOrder: 8, title: 'Comparação com a trajetória da China.' },
  { sectionCode: 'III.7', detailCode: 'III.7.9', detailSortOrder: 9, title: 'Análise comparativa das políticas e de seus resultados, considerando continuidade e coordenação institucional, demanda, financiamento, escala de produção, produtividade, aprendizado tecnológico e inserção internacional.' },
  { sectionCode: 'III.7', detailCode: 'III.7.10', detailSortOrder: 10, title: 'Identificação dos principais problemas sistêmicos e das lições para uma nova política de desenvolvimento da indústria naval brasileira.' },
  { sectionCode: 'III.8', detailCode: 'III.8.1', detailSortOrder: 1, title: 'Síntese das transformações geopolíticas e ambientais em curso, examinadas nos Tomos I e II, que afetam os mercados internacionais e a indústria naval.' },
  { sectionCode: 'III.8', detailCode: 'III.8.2', detailSortOrder: 2, title: 'Mudanças nos setores de energia, navegação e defesa.' },
  { sectionCode: 'III.8', detailCode: 'III.8.3', detailSortOrder: 3, title: 'Reorganização das cadeias produtivas, segurança econômica, transição energética e novas exigências ambientais.' },
  { sectionCode: 'III.8', detailCode: 'III.8.4', detailSortOrder: 4, title: 'Impactos sobre a distribuição geográfica da produção, o acesso a mercados e tecnologias, a demanda por embarcações e a formação de parcerias internacionais.' },
  { sectionCode: 'III.8', detailCode: 'III.8.5', detailSortOrder: 5, title: 'Riscos, desafios e oportunidades para a reestruturação da indústria naval brasileira.' },
  { sectionCode: 'III.8', detailCode: 'III.8.6', detailSortOrder: 6, title: 'Implicações para as políticas industriais e marítimas nacionais.' },
  { sectionCode: 'III.9', detailCode: 'III.9.1', detailSortOrder: 1, title: 'Síntese das condições econômicas que afetam a indústria marítima brasileira.' },
  { sectionCode: 'III.9', detailCode: 'III.9.2', detailSortOrder: 2, title: 'Volume e estabilidade da demanda, condições macroeconômicas, custo de capital, restrições fiscais, taxa de câmbio e ambiente de investimento.' },
  { sectionCode: 'III.9', detailCode: 'III.9.3', detailSortOrder: 3, title: 'Organização institucional dos órgãos do Estado com atribuições sobre a indústria marítima.' },
  { sectionCode: 'III.9', detailCode: 'III.9.4', detailSortOrder: 4, title: 'Formulação das políticas, regulamentação e regulação dos setores, fiscalização das atividades e gestão dos mecanismos de fomento e financiamento.' },
  { sectionCode: 'III.9', detailCode: 'III.9.5', detailSortOrder: 5, title: 'Avaliação da racionalidade da estrutura institucional, da coordenação entre os órgãos envolvidos e dos efeitos da ausência de orientação programática estável e consolidada.' },
  { sectionCode: 'III.9', detailCode: 'III.9.6', detailSortOrder: 6, title: 'Avaliação da capacitação técnica, autonomia decisória e continuidade institucional dos órgãos e agências envolvidos.' },
  { sectionCode: 'III.9', detailCode: 'III.9.7', detailSortOrder: 7, title: 'Riscos políticos, econômicos e regulatórios para a reestruturação da indústria naval.' },
  { sectionCode: 'III.9', detailCode: 'III.9.8', detailSortOrder: 8, title: 'Aspectos determinantes para a reorientação das políticas industriais e a implantação de novos modelos para a indústria naval, considerando suas interfaces com a marinha mercante, o óleo e gás, a defesa e a energia.' },
  { sectionCode: 'III.9', detailCode: 'III.9.9', detailSortOrder: 9, title: 'Desafios e oportunidades.' },
  { sectionCode: 'IV.1', detailCode: 'IV.1.1', detailSortOrder: 1, title: 'Consolidação dos resultados dos Tomos I, II e III.' },
  { sectionCode: 'IV.1', detailCode: 'IV.1.2', detailSortOrder: 2, title: 'Articulação entre mercados e demanda, capacidade produtiva, tecnologia, produtividade, competitividade, cadeia de suprimentos, políticas públicas e ambiente institucional.' },
  { sectionCode: 'IV.1', detailCode: 'IV.1.3', detailSortOrder: 3, title: 'Análise das relações entre volume e estabilidade da demanda, capacidade dos estaleiros, produtividade, custos, prazos, qualidade e condições de financiamento.' },
  { sectionCode: 'IV.1', detailCode: 'IV.1.4', detailSortOrder: 4, title: 'Compatibilidade entre a demanda potencial e a capacidade de atendimento da indústria brasileira nos diferentes segmentos.' },
  { sectionCode: 'IV.1', detailCode: 'IV.1.5', detailSortOrder: 5, title: 'Identificação das principais potencialidades, limitações, dependências e gargalos da indústria naval brasileira.' },
  { sectionCode: 'IV.1', detailCode: 'IV.1.6', detailSortOrder: 6, title: 'Inter-relações e possíveis sinergias entre construção naval, reparo, descomissionamento, navegação interior, óleo e gás, energias oceânicas e defesa.' },
  { sectionCode: 'IV.1', detailCode: 'IV.1.7', detailSortOrder: 7, title: 'Análise de como a descarbonização, a transição energética e as mudanças tecnológicas e geopolíticas alteram a composição da demanda, os requisitos tecnológicos e as oportunidades de inserção da indústria naval brasileira.' },
  { sectionCode: 'IV.1', detailCode: 'IV.1.8', detailSortOrder: 8, title: 'Identificação dos fatores críticos, das incertezas e das variáveis que deverão ser consideradas na construção dos cenários para a indústria naval brasileira.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.1', detailSortOrder: 1, title: 'Consolidação das projeções de demanda para transporte marítimo e navegação interior, óleo e gás offshore, energias oceânicas, defesa, reparo e descomissionamento, apresentadas nos tomos anteriores.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.2', detailSortOrder: 2, title: 'Definição de cenários alternativos e das respectivas hipóteses, horizontes temporais e principais incertezas.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.3', detailSortOrder: 3, title: 'Projeção do volume e da composição da demanda por segmento.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.4', detailSortOrder: 4, title: 'Simulação das condições necessárias para que a demanda por embarcações e serviços seja atendida pela indústria naval brasileira.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.5', detailSortOrder: 5, title: 'Diferenciais de custos e prazos de entrega, qualidade e confiabilidade, condições de financiamento, tributação, regras de utilização das contas vinculadas, regras de tripulação da bandeira brasileira, regras de preferência de bandeira e afretamento, conteúdo local e demais instrumentos regulatórios e de incentivo.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.6', detailSortOrder: 6, title: 'Efeitos sobre a competitividade da bandeira brasileira em relação às bandeiras estrangeiras e sobre a competitividade dos navios construídos no Brasil em relação aos importados.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.7', detailSortOrder: 7, title: 'Avaliação das possibilidades de inserção competitiva dos estaleiros brasileiros nos diferentes segmentos de mercado e classes de estaleiros.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.8', detailSortOrder: 8, title: 'Metas e desafios de produtividade e desempenho.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.9', detailSortOrder: 9, title: 'Avaliação das exigências tecnológicas e de recursos humanos em cada cenário.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.10', detailSortOrder: 10, title: 'Capacidades e deficiências em engenharia, projeto, produção, gestão, pesquisa e desenvolvimento e formação profissional.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.11', detailSortOrder: 11, title: 'Necessidades de qualificação, desenvolvimento e transferência de tecnologia.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.12', detailSortOrder: 12, title: 'Necessidades de investimento em modernização, ampliação ou implantação de instalações.' },
  { sectionCode: 'IV.2', detailCode: 'IV.2.13', detailSortOrder: 13, title: 'Efeitos sobre a capacidade produtiva, a cadeia de suprimentos e o potencial de produção nacional em cada cenário.' },
  { sectionCode: 'IV.3', detailCode: 'IV.3.1', detailSortOrder: 1, title: 'Síntese das principais conclusões derivadas do diagnóstico integrado e dos cenários.' },
  { sectionCode: 'IV.3', detailCode: 'IV.3.2', detailSortOrder: 2, title: 'Potencialidades, limitações, gargalos e condições necessárias para o desenvolvimento competitivo da indústria naval brasileira.' },
  { sectionCode: 'IV.3', detailCode: 'IV.3.3', detailSortOrder: 3, title: 'Explicitação do que pode ser afirmado com base nas evidências disponíveis e do que permanece condicionado por incertezas, hipóteses ou lacunas de informação.' },
  { sectionCode: 'IV.3', detailCode: 'IV.3.4', detailSortOrder: 4, title: 'Indicação das questões que deverão orientar a identificação dos segmentos estratégicos, a formulação das políticas e a elaboração do Plano de Ação.' },
  { sectionCode: 'IV.3', detailCode: 'IV.3.5', detailSortOrder: 5, title: 'O enfrentamento dessas questões será objeto do Relatório 2.' }
] as const;

export type DetailedActivityItem = (typeof DETAILED_ACTIVITY_ITEMS)[number];
