export const IDENTIFIED_INTERFACES_SEED = [
  {
    title: "Interface: I.5.11. Navegação interior e desenvolvimento regional (G7 + G1)",
    description: "Interface técnica e temática identificada no plano de atividades entre G7 — Fluvial: Transporte e Construção (líder/origem) e G1 — Sistematização (envolvidos) para a elaboração e compatibilização do item I.5.11. Navegação interior e desenvolvimento regional (Capítulo I.5: Transporte Hidroviário Interior).",
    sectionCode: "I.5",
    chapterTitle: "Transporte Hidroviário Interior",
    detailCode: "I.5.11",
    itemTitle: "Navegação interior e desenvolvimento regional",
    rawSectionTitle: "5.11. Navegação interior e desenvolvimento regional",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G7 — Fluvial: Transporte e Construção",
    involvedGroupNames: ["G1 — Sistematização"],
    allGroupNames: ["G7 — Fluvial: Transporte e Construção", "G1 — Sistematização"],
    groupCodes: ["G7", "G1"],
  },
  {
    title: "Interface: I.6.5. Embarcações de apoio e aliviadores: aspectos tecnológicos e operacionais (G6 + G4)",
    description: "Interface técnica e temática identificada no plano de atividades entre G6 — Offshore (líder/origem) e G4 — Transporte Marítimo Mundial (envolvidos) para a elaboração e compatibilização do item I.6.5. Embarcações de apoio e aliviadores: aspectos tecnológicos e operacionais (Capítulo I.6: Indústria de Óleo e Gás e de Energia Eólica Offshore).",
    sectionCode: "I.6",
    chapterTitle: "Indústria de Óleo e Gás e de Energia Eólica Offshore",
    detailCode: "I.6.5",
    itemTitle: "Embarcações de apoio e aliviadores: aspectos tecnológicos e operacionais",
    rawSectionTitle: "6.5. Embarcações de apoio e aliviadores: aspectos tecnológicos e operacionais",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G6 — Offshore",
    involvedGroupNames: ["G4 — Transporte Marítimo Mundial"],
    allGroupNames: ["G6 — Offshore", "G4 — Transporte Marítimo Mundial"],
    groupCodes: ["G6", "G4"],
  },
  {
    title: "Interface: I.6.6. Mercado internacional de embarcações de apoio e aliviadores: regiões de operação, demanda, oferta, formas de contratação e preços (G6 + G4)",
    description: "Interface técnica e temática identificada no plano de atividades entre G6 — Offshore (líder/origem) e G4 — Transporte Marítimo Mundial (envolvidos) para a elaboração e compatibilização do item I.6.6. Mercado internacional de embarcações de apoio e aliviadores: regiões de operação, demanda, oferta, formas de contratação e preços (Capítulo I.6: Indústria de Óleo e Gás e de Energia Eólica Offshore).",
    sectionCode: "I.6",
    chapterTitle: "Indústria de Óleo e Gás e de Energia Eólica Offshore",
    detailCode: "I.6.6",
    itemTitle: "Mercado internacional de embarcações de apoio e aliviadores: regiões de operação, demanda, oferta, formas de contratação e preços",
    rawSectionTitle: "6.6. Mercado internacional de embarcações de apoio e aliviadores: regiões de operação, demanda, oferta, formas de contratação e preços",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G6 — Offshore",
    involvedGroupNames: ["G4 — Transporte Marítimo Mundial"],
    allGroupNames: ["G6 — Offshore", "G4 — Transporte Marítimo Mundial"],
    groupCodes: ["G6", "G4"],
  },
  {
    title: "Interface: I.6.10. Mercado brasileiro de navios aliviadores e embarcações de apoio offshore (G6 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G6 — Offshore (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.6.10. Mercado brasileiro de navios aliviadores e embarcações de apoio offshore (Capítulo I.6: Indústria de Óleo e Gás e de Energia Eólica Offshore).",
    sectionCode: "I.6",
    chapterTitle: "Indústria de Óleo e Gás e de Energia Eólica Offshore",
    detailCode: "I.6.10",
    itemTitle: "Mercado brasileiro de navios aliviadores e embarcações de apoio offshore",
    rawSectionTitle: "6.10. Mercado brasileiro de navios aliviadores e embarcações de apoio offshore",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G6 — Offshore",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G6 — Offshore", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G6", "G3"],
  },
  {
    title: "Interface: II.1.5. Protecionismo e fatores de competitividade (G10 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G10 — Construção Naval Mundial e Análise Econômica (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.1.5. Protecionismo e fatores de competitividade (Capítulo I.1: Introdução).",
    sectionCode: "I.1",
    chapterTitle: "Introdução",
    detailCode: "II.1.5",
    itemTitle: "Protecionismo e fatores de competitividade",
    rawSectionTitle: "1.5. Protecionismo e fatores de competitividade",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G10 — Construção Naval Mundial e Análise Econômica",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G10 — Construção Naval Mundial e Análise Econômica", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G10", "G3"],
  },
  {
    title: "Interface: I.2.1. Conceito e delimitação da economia marítima (G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.2.1. Conceito e delimitação da economia marítima (Capítulo I.2: Economia Marítima).",
    sectionCode: "I.2",
    chapterTitle: "Economia Marítima",
    detailCode: "I.2.1",
    itemTitle: "Conceito e delimitação da economia marítima",
    rawSectionTitle: "2.1. Dimensões de análise das experiências nacionais: protecionismo; evolução da indústria; estrutura empresarial; especialização; qualificação tecnológica; recursos humanos; cadeia de fornecedores; inserção internacional; evolução da produtividade; competitividade; resultados produtivos; estratégias de desenvolvimento tecnológico e catching-up",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G3"],
  },
  {
    title: "Interface: I.2.2. Interdependências entre a construção naval e demais setores marítimos (G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.2.2. Interdependências entre a construção naval e demais setores marítimos (Capítulo I.2: Economia Marítima).",
    sectionCode: "I.2",
    chapterTitle: "Economia Marítima",
    detailCode: "I.2.2",
    itemTitle: "Interdependências entre a construção naval e demais setores marítimos",
    rawSectionTitle: "2.2. Japão",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G3"],
  },
  {
    title: "Interface: I.2.3. Relevância estratégica e econômica da economia marítima (G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.2.3. Relevância estratégica e econômica da economia marítima (Capítulo I.2: Economia Marítima).",
    sectionCode: "I.2",
    chapterTitle: "Economia Marítima",
    detailCode: "I.2.3",
    itemTitle: "Relevância estratégica e econômica da economia marítima",
    rawSectionTitle: "2.3. Coreia do Sul",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G3"],
  },
  {
    title: "Interface: I.2.4. Vetores de transformação: geopolítica, transição energética, cadeias globais e regulação ambiental (G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.2.4. Vetores de transformação: geopolítica, transição energética, cadeias globais e regulação ambiental (Capítulo I.2: Economia Marítima).",
    sectionCode: "I.2",
    chapterTitle: "Economia Marítima",
    detailCode: "I.2.4",
    itemTitle: "Vetores de transformação: geopolítica, transição energética, cadeias globais e regulação ambiental",
    rawSectionTitle: "2.4. China",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G3"],
  },
  {
    title: "Interface: II.2.5. Estados Unidos (G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.2.5. Estados Unidos (Capítulo I.2: Economia Marítima).",
    sectionCode: "I.2",
    chapterTitle: "Economia Marítima",
    detailCode: "II.2.5",
    itemTitle: "Estados Unidos",
    rawSectionTitle: "2.5. Singapura",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G3"],
  },
  {
    title: "Interface: II.2.6. Países europeus selecionados (G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.2.6. Países europeus selecionados (Capítulo I.2: Economia Marítima).",
    sectionCode: "I.2",
    chapterTitle: "Economia Marítima",
    detailCode: "II.2.6",
    itemTitle: "Países europeus selecionados",
    rawSectionTitle: "2.6. Estados Unidos",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G3"],
  },
  {
    title: "Interface: II.2.7. Índia (G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.2.7. Índia (Capítulo I.2: Economia Marítima).",
    sectionCode: "I.2",
    chapterTitle: "Economia Marítima",
    detailCode: "II.2.7",
    itemTitle: "Índia",
    rawSectionTitle: "2.7. Países europeus selecionados",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G3"],
  },
  {
    title: "Interface: II.2.8. Vietnã (G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.2.8. Vietnã (Capítulo I.2: Economia Marítima).",
    sectionCode: "I.2",
    chapterTitle: "Economia Marítima",
    detailCode: "II.2.8",
    itemTitle: "Vietnã",
    rawSectionTitle: "2.8. Índia",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G3"],
  },
  {
    title: "Interface: II.2.9. Indonésia (G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.2.9. Indonésia (Capítulo I.2: Economia Marítima).",
    sectionCode: "I.2",
    chapterTitle: "Economia Marítima",
    detailCode: "II.2.9",
    itemTitle: "Indonésia",
    rawSectionTitle: "2.9. Vietnã",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G3"],
  },
  {
    title: "Interface: II.2.10. Outros produtores emergentes (G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.2.10. Outros produtores emergentes (Capítulo I.2: Economia Marítima).",
    sectionCode: "I.2",
    chapterTitle: "Economia Marítima",
    detailCode: "II.2.10",
    itemTitle: "Outros produtores emergentes",
    rawSectionTitle: "2.10. Indonésia",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G3"],
  },
  {
    title: "Interface: III.2.11. Austrália e Nova Zelândia (G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item III.2.11. Austrália e Nova Zelândia (Capítulo III.2: Políticas de marinha mercante no mundo).",
    sectionCode: "III.2",
    chapterTitle: "Políticas de marinha mercante no mundo",
    detailCode: "III.2.11",
    itemTitle: "Austrália e Nova Zelândia",
    rawSectionTitle: "2.11. Outros produtores emergentes",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G3"],
  },
  {
    title: "Interface: I.4.3. Regulamentação do transporte marítimo no Brasil (G11 + G7)",
    description: "Interface técnica e temática identificada no plano de atividades entre G11 — Construção Naval no Brasil (líder/origem) e G7 — Fluvial: Transporte e Construção (envolvidos) para a elaboração e compatibilização do item I.4.3. Regulamentação do transporte marítimo no Brasil (Capítulo I.4: Transporte Marítimo no Brasil).",
    sectionCode: "I.4",
    chapterTitle: "Transporte Marítimo no Brasil",
    detailCode: "I.4.3",
    itemTitle: "Regulamentação do transporte marítimo no Brasil",
    rawSectionTitle: "4.3. Estaleiros de construção de embarcações fluviais",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G11 — Construção Naval no Brasil",
    involvedGroupNames: ["G7 — Fluvial: Transporte e Construção"],
    allGroupNames: ["G11 — Construção Naval no Brasil", "G7 — Fluvial: Transporte e Construção"],
    groupCodes: ["G11", "G7"],
  },
  {
    title: "Interface: I.4.4. Estrutura e organização dos mercados: empresas, frotas, bandeiras e afretamento (G11 + G6)",
    description: "Interface técnica e temática identificada no plano de atividades entre G11 — Construção Naval no Brasil (líder/origem) e G6 — Offshore (envolvidos) para a elaboração e compatibilização do item I.4.4. Estrutura e organização dos mercados: empresas, frotas, bandeiras e afretamento (Capítulo I.4: Transporte Marítimo no Brasil).",
    sectionCode: "I.4",
    chapterTitle: "Transporte Marítimo no Brasil",
    detailCode: "I.4.4",
    itemTitle: "Estrutura e organização dos mercados: empresas, frotas, bandeiras e afretamento",
    rawSectionTitle: "4.4. Estaleiros e instalações para construção de unidades offshore, fabricação e integração de módulos",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G11 — Construção Naval no Brasil",
    involvedGroupNames: ["G6 — Offshore"],
    allGroupNames: ["G11 — Construção Naval no Brasil", "G6 — Offshore"],
    groupCodes: ["G11", "G6"],
  },
  {
    title: "Interface: I.4.5. Integração às redes mundiais de transporte marítimo (G11 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G11 — Construção Naval no Brasil (líder/origem) e G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item I.4.5. Integração às redes mundiais de transporte marítimo (Capítulo I.4: Transporte Marítimo no Brasil).",
    sectionCode: "I.4",
    chapterTitle: "Transporte Marítimo no Brasil",
    detailCode: "I.4.5",
    itemTitle: "Integração às redes mundiais de transporte marítimo",
    rawSectionTitle: "4.5. Estaleiros de construção naval militar",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G11 — Construção Naval no Brasil",
    involvedGroupNames: ["G9 — Construção Militar"],
    allGroupNames: ["G11 — Construção Naval no Brasil", "G9 — Construção Militar"],
    groupCodes: ["G11", "G9"],
  },
  {
    title: "Interface: I.4.6. Apoio portuário e apoio marítimo (G11 + G2)",
    description: "Interface técnica e temática identificada no plano de atividades entre G11 — Construção Naval no Brasil (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos (envolvidos) para a elaboração e compatibilização do item I.4.6. Apoio portuário e apoio marítimo (Capítulo I.4: Transporte Marítimo no Brasil).",
    sectionCode: "I.4",
    chapterTitle: "Transporte Marítimo no Brasil",
    detailCode: "I.4.6",
    itemTitle: "Apoio portuário e apoio marítimo",
    rawSectionTitle: "4.6. Cadeia produtiva, por tipo de produto e região",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G11 — Construção Naval no Brasil",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos"],
    allGroupNames: ["G11 — Construção Naval no Brasil", "G2 — Política Industrial e Cadeia de Suprimentos"],
    groupCodes: ["G11", "G2"],
  },
  {
    title: "Interface: I.5.3. Principais tipos de embarcações: aspectos tecnológicos e operacionais (G11 + G9 + G6)",
    description: "Interface técnica e temática identificada no plano de atividades entre G11 — Construção Naval no Brasil (líder/origem) e G9 — Construção Militar, G6 — Offshore (envolvidos) para a elaboração e compatibilização do item I.5.3. Principais tipos de embarcações: aspectos tecnológicos e operacionais (Capítulo I.5: Transporte Hidroviário Interior).",
    sectionCode: "I.5",
    chapterTitle: "Transporte Hidroviário Interior",
    detailCode: "I.5.3",
    itemTitle: "Principais tipos de embarcações: aspectos tecnológicos e operacionais",
    rawSectionTitle: "5.3. Regulamentação internacional do desmantelamento e reciclagem de navios: Convenção de Hong Kong e requisitos ambientais",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G11 — Construção Naval no Brasil",
    involvedGroupNames: ["G9 — Construção Militar", "G6 — Offshore"],
    allGroupNames: ["G11 — Construção Naval no Brasil", "G9 — Construção Militar", "G6 — Offshore"],
    groupCodes: ["G11", "G9", "G6"],
  },
  {
    title: "Interface: I.5.4. Infraestrutura e condições de navegabilidade (G11 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G11 — Construção Naval no Brasil (líder/origem) e G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item I.5.4. Infraestrutura e condições de navegabilidade (Capítulo I.5: Transporte Hidroviário Interior).",
    sectionCode: "I.5",
    chapterTitle: "Transporte Hidroviário Interior",
    detailCode: "I.5.4",
    itemTitle: "Infraestrutura e condições de navegabilidade",
    rawSectionTitle: "5.4. Mercado mundial de desmantelamento e reciclagem de navios: estrutura, principais polos e tendências",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G11 — Construção Naval no Brasil",
    involvedGroupNames: ["G9 — Construção Militar"],
    allGroupNames: ["G11 — Construção Naval no Brasil", "G9 — Construção Militar"],
    groupCodes: ["G11", "G9"],
  },
  {
    title: "Interface: I.5.5. Fluxos e estrutura das operações (G11 + G6)",
    description: "Interface técnica e temática identificada no plano de atividades entre G11 — Construção Naval no Brasil (líder/origem) e G6 — Offshore (envolvidos) para a elaboração e compatibilização do item I.5.5. Fluxos e estrutura das operações (Capítulo I.5: Transporte Hidroviário Interior).",
    sectionCode: "I.5",
    chapterTitle: "Transporte Hidroviário Interior",
    detailCode: "I.5.5",
    itemTitle: "Fluxos e estrutura das operações",
    rawSectionTitle: "5.5. Descomissionamento de unidades offshore: características, regulamentação e mercado mundial",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G11 — Construção Naval no Brasil",
    involvedGroupNames: ["G6 — Offshore"],
    allGroupNames: ["G11 — Construção Naval no Brasil", "G6 — Offshore"],
    groupCodes: ["G11", "G6"],
  },
  {
    title: "Interface: I.5.6. Empresas e frotas (G11 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G11 — Construção Naval no Brasil (líder/origem) e G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item I.5.6. Empresas e frotas (Capítulo I.5: Transporte Hidroviário Interior).",
    sectionCode: "I.5",
    chapterTitle: "Transporte Hidroviário Interior",
    detailCode: "I.5.6",
    itemTitle: "Empresas e frotas",
    rawSectionTitle: "5.6. Regulamentação brasileira do desmantelamento e reciclagem de navios e plataformas",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G11 — Construção Naval no Brasil",
    involvedGroupNames: ["G9 — Construção Militar"],
    allGroupNames: ["G11 — Construção Naval no Brasil", "G9 — Construção Militar"],
    groupCodes: ["G11", "G9"],
  },
  {
    title: "Interface: I.5.7. Transporte multimodal (G4 + G8)",
    description: "Interface técnica e temática identificada no plano de atividades entre G4 — Transporte Marítimo Mundial (líder/origem) e G8 — Descarbonização (envolvidos) para a elaboração e compatibilização do item I.5.7. Transporte multimodal (Capítulo I.5: Transporte Hidroviário Interior).",
    sectionCode: "I.5",
    chapterTitle: "Transporte Hidroviário Interior",
    detailCode: "I.5.7",
    itemTitle: "Transporte multimodal",
    rawSectionTitle: "5.7. Demanda brasileira por reparo, docagem e retrofitting de embarcações",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G4 — Transporte Marítimo Mundial",
    involvedGroupNames: ["G8 — Descarbonização"],
    allGroupNames: ["G4 — Transporte Marítimo Mundial", "G8 — Descarbonização"],
    groupCodes: ["G4", "G8"],
  },
  {
    title: "Interface: I.5.10. Transporte hidroviário urbano (G11 + G1)",
    description: "Interface técnica e temática identificada no plano de atividades entre G11 — Construção Naval no Brasil (líder/origem) e G1 — Sistematização (envolvidos) para a elaboração e compatibilização do item I.5.10. Transporte hidroviário urbano (Capítulo I.5: Transporte Hidroviário Interior).",
    sectionCode: "I.5",
    chapterTitle: "Transporte Hidroviário Interior",
    detailCode: "I.5.10",
    itemTitle: "Transporte hidroviário urbano",
    rawSectionTitle: "5.10. Competição internacional e competitividade das atividades no Brasil",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G11 — Construção Naval no Brasil",
    involvedGroupNames: ["G1 — Sistematização"],
    allGroupNames: ["G11 — Construção Naval no Brasil", "G1 — Sistematização"],
    groupCodes: ["G11", "G1"],
  },
  {
    title: "Interface: I.5.11. Navegação interior e desenvolvimento regional (G11 + G1)",
    description: "Interface técnica e temática identificada no plano de atividades entre G11 — Construção Naval no Brasil (líder/origem) e G1 — Sistematização (envolvidos) para a elaboração e compatibilização do item I.5.11. Navegação interior e desenvolvimento regional (Capítulo I.5: Transporte Hidroviário Interior).",
    sectionCode: "I.5",
    chapterTitle: "Transporte Hidroviário Interior",
    detailCode: "I.5.11",
    itemTitle: "Navegação interior e desenvolvimento regional",
    rawSectionTitle: "5.11. Desafios e oportunidades para reparo, retrofitting, desmantelamento e descomissionamento no Brasil",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G11 — Construção Naval no Brasil",
    involvedGroupNames: ["G1 — Sistematização"],
    allGroupNames: ["G11 — Construção Naval no Brasil", "G1 — Sistematização"],
    groupCodes: ["G11", "G1"],
  },
  {
    title: "Interface: I.6.1. Evolução e perspectivas da indústria mundial de óleo e gás offshore (G2 + G11)",
    description: "Interface técnica e temática identificada no plano de atividades entre G2 — Política Industrial e Cadeia de Suprimentos (líder/origem) e G11 — Construção Naval no Brasil (envolvidos) para a elaboração e compatibilização do item I.6.1. Evolução e perspectivas da indústria mundial de óleo e gás offshore (Capítulo I.6: Indústria de Óleo e Gás e de Energia Eólica Offshore).",
    sectionCode: "I.6",
    chapterTitle: "Indústria de Óleo e Gás e de Energia Eólica Offshore",
    detailCode: "I.6.1",
    itemTitle: "Evolução e perspectivas da indústria mundial de óleo e gás offshore",
    rawSectionTitle: "6.1. Estrutura da cadeia produtiva da construção naval: principais segmentos, produtos e relações entre estaleiros e fornecedores",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G2 — Política Industrial e Cadeia de Suprimentos",
    involvedGroupNames: ["G11 — Construção Naval no Brasil"],
    allGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G11 — Construção Naval no Brasil"],
    groupCodes: ["G2", "G11"],
  },
  {
    title: "Interface: I.6.5. Embarcações de apoio e aliviadores: aspectos tecnológicos e operacionais (G10 + G11 + G2)",
    description: "Interface técnica e temática identificada no plano de atividades entre G10 — Construção Naval Mundial e Análise Econômica (líder/origem) e G11 — Construção Naval no Brasil, G2 — Política Industrial e Cadeia de Suprimentos (envolvidos) para a elaboração e compatibilização do item I.6.5. Embarcações de apoio e aliviadores: aspectos tecnológicos e operacionais (Capítulo I.6: Indústria de Óleo e Gás e de Energia Eólica Offshore).",
    sectionCode: "I.6",
    chapterTitle: "Indústria de Óleo e Gás e de Energia Eólica Offshore",
    detailCode: "I.6.5",
    itemTitle: "Embarcações de apoio e aliviadores: aspectos tecnológicos e operacionais",
    rawSectionTitle: "6.5. Estrutura atual da cadeia de fornecedores da indústria naval brasileira",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G10 — Construção Naval Mundial e Análise Econômica",
    involvedGroupNames: ["G11 — Construção Naval no Brasil", "G2 — Política Industrial e Cadeia de Suprimentos"],
    allGroupNames: ["G10 — Construção Naval Mundial e Análise Econômica", "G11 — Construção Naval no Brasil", "G2 — Política Industrial e Cadeia de Suprimentos"],
    groupCodes: ["G10", "G11", "G2"],
  },
  {
    title: "Interface: I.6.7. Atividade offshore no Brasil: campos, empresas e perspectivas (G11 + G2)",
    description: "Interface técnica e temática identificada no plano de atividades entre G11 — Construção Naval no Brasil (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos (envolvidos) para a elaboração e compatibilização do item I.6.7. Atividade offshore no Brasil: campos, empresas e perspectivas (Capítulo I.6: Indústria de Óleo e Gás e de Energia Eólica Offshore).",
    sectionCode: "I.6",
    chapterTitle: "Indústria de Óleo e Gás e de Energia Eólica Offshore",
    detailCode: "I.6.7",
    itemTitle: "Atividade offshore no Brasil: campos, empresas e perspectivas",
    rawSectionTitle: "6.7. Distribuição regional e capacidade dos fornecedores nacionais",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G11 — Construção Naval no Brasil",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos"],
    allGroupNames: ["G11 — Construção Naval no Brasil", "G2 — Política Industrial e Cadeia de Suprimentos"],
    groupCodes: ["G11", "G2"],
  },
  {
    title: "Interface: I.8.1. Direcionadores globais, metas e regulamentação internacional da descarbonização marítima (G10 + G11)",
    description: "Interface técnica e temática identificada no plano de atividades entre G10 — Construção Naval Mundial e Análise Econômica (líder/origem) e G11 — Construção Naval no Brasil (envolvidos) para a elaboração e compatibilização do item I.8.1. Direcionadores globais, metas e regulamentação internacional da descarbonização marítima (Capítulo I.8: Descarbonização na Indústria Marítima).",
    sectionCode: "I.8",
    chapterTitle: "Descarbonização na Indústria Marítima",
    detailCode: "I.8.1",
    itemTitle: "Direcionadores globais, metas e regulamentação internacional da descarbonização marítima",
    rawSectionTitle: "8.1. Metodologia e indicadores para avaliação tecnológica, de produtividade e desempenho dos estaleiros",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G10 — Construção Naval Mundial e Análise Econômica",
    involvedGroupNames: ["G11 — Construção Naval no Brasil"],
    allGroupNames: ["G10 — Construção Naval Mundial e Análise Econômica", "G11 — Construção Naval no Brasil"],
    groupCodes: ["G10", "G11"],
  },
  {
    title: "Interface: I.8.3. Respostas de armadores, operadores, portos e fornecedores de energia à descarbonização (G10 + G11)",
    description: "Interface técnica e temática identificada no plano de atividades entre G10 — Construção Naval Mundial e Análise Econômica (líder/origem) e G11 — Construção Naval no Brasil (envolvidos) para a elaboração e compatibilização do item I.8.3. Respostas de armadores, operadores, portos e fornecedores de energia à descarbonização (Capítulo I.8: Descarbonização na Indústria Marítima).",
    sectionCode: "I.8",
    chapterTitle: "Descarbonização na Indústria Marítima",
    detailCode: "I.8.3",
    itemTitle: "Respostas de armadores, operadores, portos e fornecedores de energia à descarbonização",
    rawSectionTitle: "8.3. Padrões tecnológicos, produtividade e desempenho dos estaleiros brasileiros nos últimos períodos de operação contínua, na situação atual e potencial",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G10 — Construção Naval Mundial e Análise Econômica",
    involvedGroupNames: ["G11 — Construção Naval no Brasil"],
    allGroupNames: ["G10 — Construção Naval Mundial e Análise Econômica", "G11 — Construção Naval no Brasil"],
    groupCodes: ["G10", "G11"],
  },
  {
    title: "Interface: I.8.4. Combustíveis marítimos alternativos: características, disponibilidade, custos e perspectivas (G10 + G11)",
    description: "Interface técnica e temática identificada no plano de atividades entre G10 — Construção Naval Mundial e Análise Econômica (líder/origem) e G11 — Construção Naval no Brasil (envolvidos) para a elaboração e compatibilização do item I.8.4. Combustíveis marítimos alternativos: características, disponibilidade, custos e perspectivas (Capítulo I.8: Descarbonização na Indústria Marítima).",
    sectionCode: "I.8",
    chapterTitle: "Descarbonização na Indústria Marítima",
    detailCode: "I.8.4",
    itemTitle: "Combustíveis marítimos alternativos: características, disponibilidade, custos e perspectivas",
    rawSectionTitle: "8.4. Benchmarking dos estaleiros brasileiros em relação às classes internacionais relevantes",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G10 — Construção Naval Mundial e Análise Econômica",
    involvedGroupNames: ["G11 — Construção Naval no Brasil"],
    allGroupNames: ["G10 — Construção Naval Mundial e Análise Econômica", "G11 — Construção Naval no Brasil"],
    groupCodes: ["G10", "G11"],
  },
  {
    title: "Interface: I.8.5. Tecnologias de eficiência energética e redução de emissões: casco, propulsão, sistemas de controle e digitalização (G10 + G11)",
    description: "Interface técnica e temática identificada no plano de atividades entre G10 — Construção Naval Mundial e Análise Econômica (líder/origem) e G11 — Construção Naval no Brasil (envolvidos) para a elaboração e compatibilização do item I.8.5. Tecnologias de eficiência energética e redução de emissões: casco, propulsão, sistemas de controle e digitalização (Capítulo I.8: Descarbonização na Indústria Marítima).",
    sectionCode: "I.8",
    chapterTitle: "Descarbonização na Indústria Marítima",
    detailCode: "I.8.5",
    itemTitle: "Tecnologias de eficiência energética e redução de emissões: casco, propulsão, sistemas de controle e digitalização",
    rawSectionTitle: "8.5. Potencialidades, limitações e gargalos de produtividade e competitividade dos estaleiros brasileiros",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G10 — Construção Naval Mundial e Análise Econômica",
    involvedGroupNames: ["G11 — Construção Naval no Brasil"],
    allGroupNames: ["G10 — Construção Naval Mundial e Análise Econômica", "G11 — Construção Naval no Brasil"],
    groupCodes: ["G10", "G11"],
  },
  {
    title: "Interface: II.1.6. Estrutura e integração da cadeia produtiva (G2 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G2 — Política Industrial e Cadeia de Suprimentos (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.1.6. Estrutura e integração da cadeia produtiva (Capítulo I.1: Introdução).",
    sectionCode: "I.1",
    chapterTitle: "Introdução",
    detailCode: "II.1.6",
    itemTitle: "Estrutura e integração da cadeia produtiva",
    rawSectionTitle: "1.6. Metodologia para análise da evolução das políticas setoriais voltadas para a indústria naval no Brasil e no mundo",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G2 — Política Industrial e Cadeia de Suprimentos",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G2", "G3"],
  },
  {
    title: "Interface: III.1.8. Políticas públicas e mecanismos de fomento à descarbonização marítima e sua aplicabilidade ao Brasil (G2 + G8)",
    description: "Interface técnica e temática identificada no plano de atividades entre G2 — Política Industrial e Cadeia de Suprimentos (líder/origem) e G8 — Descarbonização (envolvidos) para a elaboração e compatibilização do item III.1.8. Políticas públicas e mecanismos de fomento à descarbonização marítima e sua aplicabilidade ao Brasil (Capítulo III.1: Fundamentos e tendências).",
    sectionCode: "III.1",
    chapterTitle: "Fundamentos e tendências",
    detailCode: "III.1.8",
    itemTitle: "Políticas públicas e mecanismos de fomento à descarbonização marítima e sua aplicabilidade ao Brasil",
    rawSectionTitle: "1.8. Políticas públicas e mecanismos de fomento à descarbonização marítima e sua aplicabilidade ao Brasil",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G2 — Política Industrial e Cadeia de Suprimentos",
    involvedGroupNames: ["G8 — Descarbonização"],
    allGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização"],
    groupCodes: ["G2", "G8"],
  },
  {
    title: "Interface: I.2.1. Conceito e delimitação da economia marítima (G2 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G2 — Política Industrial e Cadeia de Suprimentos (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.2.1. Conceito e delimitação da economia marítima (Capítulo I.2: Economia Marítima).",
    sectionCode: "I.2",
    chapterTitle: "Economia Marítima",
    detailCode: "I.2.1",
    itemTitle: "Conceito e delimitação da economia marítima",
    rawSectionTitle: "2.1. Justificativas econômicas, estratégicas e geopolíticas para políticas de marinha mercante",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G2 — Política Industrial e Cadeia de Suprimentos",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G2", "G3"],
  },
  {
    title: "Interface: I.3.1. Evolução do comércio e do transporte marítimo mundial (G2 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G2 — Política Industrial e Cadeia de Suprimentos (líder/origem) e G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.3.1. Evolução do comércio e do transporte marítimo mundial (Capítulo I.3: Transporte Marítimo Mundial).",
    sectionCode: "I.3",
    chapterTitle: "Transporte Marítimo Mundial",
    detailCode: "I.3.1",
    itemTitle: "Evolução do comércio e do transporte marítimo mundial",
    rawSectionTitle: "3.1. Justificativas econômicas, estratégicas e geopolíticas para políticas de CN",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G2 — Política Industrial e Cadeia de Suprimentos",
    involvedGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G2", "G3"],
  },
  {
    title: "Interface: I.4.7. Custos diferenciais da bandeira brasileira (G3 + G5)",
    description: "Interface técnica e temática identificada no plano de atividades entre G3 — Transporte Marítimo Brasil e Políticas Marítimas (líder/origem) e G5 — Fundo da Marinha Mercante (envolvidos) para a elaboração e compatibilização do item I.4.7. Custos diferenciais da bandeira brasileira (Capítulo I.4: Transporte Marítimo no Brasil).",
    sectionCode: "I.4",
    chapterTitle: "Transporte Marítimo no Brasil",
    detailCode: "I.4.7",
    itemTitle: "Custos diferenciais da bandeira brasileira",
    rawSectionTitle: "4.7. Financiamento e outros instrumentos financeiros",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G3 — Transporte Marítimo Brasil e Políticas Marítimas",
    involvedGroupNames: ["G5 — Fundo da Marinha Mercante"],
    allGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G5 — Fundo da Marinha Mercante"],
    groupCodes: ["G3", "G5"],
  },
  {
    title: "Interface: I.4.8. Panorama do setor pesqueiro (G3 + G1)",
    description: "Interface técnica e temática identificada no plano de atividades entre G3 — Transporte Marítimo Brasil e Políticas Marítimas (líder/origem) e G1 — Sistematização (envolvidos) para a elaboração e compatibilização do item I.4.8. Panorama do setor pesqueiro (Capítulo I.4: Transporte Marítimo no Brasil).",
    sectionCode: "I.4",
    chapterTitle: "Transporte Marítimo no Brasil",
    detailCode: "I.4.8",
    itemTitle: "Panorama do setor pesqueiro",
    rawSectionTitle: "4.8. Políticas de pesquisa, desenvolvimento, inovação e formação de recursos humanos",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G3 — Transporte Marítimo Brasil e Políticas Marítimas",
    involvedGroupNames: ["G1 — Sistematização"],
    allGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G1 — Sistematização"],
    groupCodes: ["G3", "G1"],
  },
  {
    title: "Interface: III.4.10. Políticas para os setores de óleo e gás, defesa e energia e seus impactos sobre a indústria naval (G3 + G2 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G3 — Transporte Marítimo Brasil e Políticas Marítimas (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item III.4.10. Políticas para os setores de óleo e gás, defesa e energia e seus impactos sobre a indústria naval (Capítulo III.4: Políticas brasileiras de marinha mercante e construção naval).",
    sectionCode: "III.4",
    chapterTitle: "Políticas brasileiras de marinha mercante e construção naval",
    detailCode: "III.4.10",
    itemTitle: "Políticas para os setores de óleo e gás, defesa e energia e seus impactos sobre a indústria naval",
    rawSectionTitle: "4.10. Políticas para os setores de óleo e gás, defesa e energia e seus impactos sobre a indústria naval",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G3 — Transporte Marítimo Brasil e Políticas Marítimas",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G9 — Construção Militar"],
    allGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G2 — Política Industrial e Cadeia de Suprimentos", "G9 — Construção Militar"],
    groupCodes: ["G3", "G2", "G9"],
  },
  {
    title: "Interface: III.4.11. Resultados das políticas brasileiras de marinha mercante e construção naval (G3 + G1)",
    description: "Interface técnica e temática identificada no plano de atividades entre G3 — Transporte Marítimo Brasil e Políticas Marítimas (líder/origem) e G1 — Sistematização (envolvidos) para a elaboração e compatibilização do item III.4.11. Resultados das políticas brasileiras de marinha mercante e construção naval (Capítulo III.4: Políticas brasileiras de marinha mercante e construção naval).",
    sectionCode: "III.4",
    chapterTitle: "Políticas brasileiras de marinha mercante e construção naval",
    detailCode: "III.4.11",
    itemTitle: "Resultados das políticas brasileiras de marinha mercante e construção naval",
    rawSectionTitle: "4.11. Resultados das políticas brasileiras de marinha mercante e construção naval",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G3 — Transporte Marítimo Brasil e Políticas Marítimas",
    involvedGroupNames: ["G1 — Sistematização"],
    allGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G1 — Sistematização"],
    groupCodes: ["G3", "G1"],
  },
  {
    title: "Interface: III.4.12. Mudanças recentes e principais questões em debate no Brasil (G3 + G1)",
    description: "Interface técnica e temática identificada no plano de atividades entre G3 — Transporte Marítimo Brasil e Políticas Marítimas (líder/origem) e G1 — Sistematização (envolvidos) para a elaboração e compatibilização do item III.4.12. Mudanças recentes e principais questões em debate no Brasil (Capítulo III.4: Políticas brasileiras de marinha mercante e construção naval).",
    sectionCode: "III.4",
    chapterTitle: "Políticas brasileiras de marinha mercante e construção naval",
    detailCode: "III.4.12",
    itemTitle: "Mudanças recentes e principais questões em debate no Brasil",
    rawSectionTitle: "4.12. Mudanças recentes e principais questões em debate no Brasil",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G3 — Transporte Marítimo Brasil e Políticas Marítimas",
    involvedGroupNames: ["G1 — Sistematização"],
    allGroupNames: ["G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G1 — Sistematização"],
    groupCodes: ["G3", "G1"],
  },
  {
    title: "Interface: I.5.8. Navegação fluvial de percurso internacional (G5 + G1 + G2)",
    description: "Interface técnica e temática identificada no plano de atividades entre G5 — Fundo da Marinha Mercante (líder/origem) e G1 — Sistematização, G2 — Política Industrial e Cadeia de Suprimentos (envolvidos) para a elaboração e compatibilização do item I.5.8. Navegação fluvial de percurso internacional (Capítulo I.5: Transporte Hidroviário Interior).",
    sectionCode: "I.5",
    chapterTitle: "Transporte Hidroviário Interior",
    detailCode: "I.5.8",
    itemTitle: "Navegação fluvial de percurso internacional",
    rawSectionTitle: "5.8. Alocação de custos e benefícios: efeitos distributivos intersetoriais e inter-regionais",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G5 — Fundo da Marinha Mercante",
    involvedGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos"],
    allGroupNames: ["G5 — Fundo da Marinha Mercante", "G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos"],
    groupCodes: ["G5", "G1", "G2"],
  },
  {
    title: "Interface: I.5.9. Transporte de passageiros na Região Amazônica (G5 + G1 + G2)",
    description: "Interface técnica e temática identificada no plano de atividades entre G5 — Fundo da Marinha Mercante (líder/origem) e G1 — Sistematização, G2 — Política Industrial e Cadeia de Suprimentos (envolvidos) para a elaboração e compatibilização do item I.5.9. Transporte de passageiros na Região Amazônica (Capítulo I.5: Transporte Hidroviário Interior).",
    sectionCode: "I.5",
    chapterTitle: "Transporte Hidroviário Interior",
    detailCode: "I.5.9",
    itemTitle: "Transporte de passageiros na Região Amazônica",
    rawSectionTitle: "5.9. Justificativa econômica e estratégica do modelo atual por segmento da navegação",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G5 — Fundo da Marinha Mercante",
    involvedGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos"],
    allGroupNames: ["G5 — Fundo da Marinha Mercante", "G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos"],
    groupCodes: ["G5", "G1", "G2"],
  },
  {
    title: "Interface: I.6.1. Evolução e perspectivas da indústria mundial de óleo e gás offshore (G2 + G1 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G2 — Política Industrial e Cadeia de Suprimentos (líder/origem) e G1 — Sistematização, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.6.1. Evolução e perspectivas da indústria mundial de óleo e gás offshore (Capítulo I.6: Indústria de Óleo e Gás e de Energia Eólica Offshore).",
    sectionCode: "I.6",
    chapterTitle: "Indústria de Óleo e Gás e de Energia Eólica Offshore",
    detailCode: "I.6.1",
    itemTitle: "Evolução e perspectivas da indústria mundial de óleo e gás offshore",
    rawSectionTitle: "6.1. Políticas industriais e perfil de nacionalização da cadeia de suprimentos da indústria naval nos principais países produtores",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G2 — Política Industrial e Cadeia de Suprimentos",
    involvedGroupNames: ["G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G1 — Sistematização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G2", "G1", "G3"],
  },
  {
    title: "Interface: I.6.2. Marcos regulatórios nos principais polos (G2 + G11)",
    description: "Interface técnica e temática identificada no plano de atividades entre G2 — Política Industrial e Cadeia de Suprimentos (líder/origem) e G11 — Construção Naval no Brasil (envolvidos) para a elaboração e compatibilização do item I.6.2. Marcos regulatórios nos principais polos (Capítulo I.6: Indústria de Óleo e Gás e de Energia Eólica Offshore).",
    sectionCode: "I.6",
    chapterTitle: "Indústria de Óleo e Gás e de Energia Eólica Offshore",
    detailCode: "I.6.2",
    itemTitle: "Marcos regulatórios nos principais polos",
    rawSectionTitle: "6.2. Importância da siderurgia e da indústria de materiais e equipamentos navais para a construção naval",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G2 — Política Industrial e Cadeia de Suprimentos",
    involvedGroupNames: ["G11 — Construção Naval no Brasil"],
    allGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G11 — Construção Naval no Brasil"],
    groupCodes: ["G2", "G11"],
  },
  {
    title: "Interface: I.6.8. Frota e demanda por unidades flutuantes de produção e sondas no Brasil (G2 + G11)",
    description: "Interface técnica e temática identificada no plano de atividades entre G2 — Política Industrial e Cadeia de Suprimentos (líder/origem) e G11 — Construção Naval no Brasil (envolvidos) para a elaboração e compatibilização do item I.6.8. Frota e demanda por unidades flutuantes de produção e sondas no Brasil (Capítulo I.6: Indústria de Óleo e Gás e de Energia Eólica Offshore).",
    sectionCode: "I.6",
    chapterTitle: "Indústria de Óleo e Gás e de Energia Eólica Offshore",
    detailCode: "I.6.8",
    itemTitle: "Frota e demanda por unidades flutuantes de produção e sondas no Brasil",
    rawSectionTitle: "6.8. Importância do desenvolvimento da cadeia nacional de suprimentos para a competitividade da indústria naval brasileira",
    tome: "Tomo I",
    interfaceType: "interface" as const,
    leadGroupName: "G2 — Política Industrial e Cadeia de Suprimentos",
    involvedGroupNames: ["G11 — Construção Naval no Brasil"],
    allGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G11 — Construção Naval no Brasil"],
    groupCodes: ["G2", "G11"],
  },
  {
    title: "Interface: I.7.1. Construção naval militar no mundo: políticas navais e modelos de governança (G1 + G2 + G3 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas, G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item I.7.1. Construção naval militar no mundo: políticas navais e modelos de governança (Capítulo I.7: Construção naval militar).",
    sectionCode: "I.7",
    chapterTitle: "Construção naval militar",
    detailCode: "I.7.1",
    itemTitle: "Construção naval militar no mundo: políticas navais e modelos de governança",
    rawSectionTitle: "7.1. O ciclo das décadas de 1970 e 1980 no Brasil: objetivos, instrumentos e resultados",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    groupCodes: ["G1", "G2", "G3", "G9"],
  },
  {
    title: "Interface: I.7.2. Principais tipos de navios e embarcações militares: aspectos tecnológicos e operacionais (G1 + G2 + G3 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas, G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item I.7.2. Principais tipos de navios e embarcações militares: aspectos tecnológicos e operacionais (Capítulo I.7: Construção naval militar).",
    sectionCode: "I.7",
    chapterTitle: "Construção naval militar",
    detailCode: "I.7.2",
    itemTitle: "Principais tipos de navios e embarcações militares: aspectos tecnológicos e operacionais",
    rawSectionTitle: "7.2. Fatores endógenos e exógenos da crise e retração nas décadas de 1980 e 1990",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    groupCodes: ["G1", "G2", "G3", "G9"],
  },
  {
    title: "Interface: I.7.3. Evolução da construção naval militar no Brasil (G1 + G2 + G3 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas, G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item I.7.3. Evolução da construção naval militar no Brasil (Capítulo I.7: Construção naval militar).",
    sectionCode: "I.7",
    chapterTitle: "Construção naval militar",
    detailCode: "I.7.3",
    itemTitle: "Evolução da construção naval militar no Brasil",
    rawSectionTitle: "7.3. Brasil e Coreia do Sul: análise comparada das trajetórias da indústria naval",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    groupCodes: ["G1", "G2", "G3", "G9"],
  },
  {
    title: "Interface: I.7.4. Programas navais em curso e previstos (G1 + G2 + G3 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas, G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item I.7.4. Programas navais em curso e previstos (Capítulo I.7: Construção naval militar).",
    sectionCode: "I.7",
    chapterTitle: "Construção naval militar",
    detailCode: "I.7.4",
    itemTitle: "Programas navais em curso e previstos",
    rawSectionTitle: "7.4. O ciclo das décadas de 2000 e 2010 no Brasil: objetivos, instrumentos e resultados",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    groupCodes: ["G1", "G2", "G3", "G9"],
  },
  {
    title: "Interface: I.7.5. Programas de offset, clusters navais e estratégias de inovação (G1 + G2 + G3 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas, G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item I.7.5. Programas de offset, clusters navais e estratégias de inovação (Capítulo I.7: Construção naval militar).",
    sectionCode: "I.7",
    chapterTitle: "Construção naval militar",
    detailCode: "I.7.5",
    itemTitle: "Programas de offset, clusters navais e estratégias de inovação",
    rawSectionTitle: "7.5. Fatores determinantes da retração da indústria naval brasileira após o ciclo de expansão dos anos 2000",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    groupCodes: ["G1", "G2", "G3", "G9"],
  },
  {
    title: "Interface: I.7.6. Participação da indústria local e processos de transferência de tecnologia (G1 + G2 + G3 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas, G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item I.7.6. Participação da indústria local e processos de transferência de tecnologia (Capítulo I.7: Construção naval militar).",
    sectionCode: "I.7",
    chapterTitle: "Construção naval militar",
    detailCode: "I.7.6",
    itemTitle: "Participação da indústria local e processos de transferência de tecnologia",
    rawSectionTitle: "7.6. Brasil e China: análise comparada das trajetórias da indústria naval a partir dos anos 2000",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    groupCodes: ["G1", "G2", "G3", "G9"],
  },
  {
    title: "Interface: I.7.7. Gargalos econômicos, produtivos e tecnológicos (G1 + G2 + G3 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas, G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item I.7.7. Gargalos econômicos, produtivos e tecnológicos (Capítulo I.7: Construção naval militar).",
    sectionCode: "I.7",
    chapterTitle: "Construção naval militar",
    detailCode: "I.7.7",
    itemTitle: "Gargalos econômicos, produtivos e tecnológicos",
    rawSectionTitle: "7.7. Análise comparativa dos ciclos brasileiros: continuidade e coordenação institucional, demanda, financiamento, escala de produção, produtividade, aprendizado tecnológico e inserção internacional",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    groupCodes: ["G1", "G2", "G3", "G9"],
  },
  {
    title: "Interface: I.7.8. Oportunidades para inserção nas cadeias globais (G1 + G2 + G3 + G9)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas, G9 — Construção Militar (envolvidos) para a elaboração e compatibilização do item I.7.8. Oportunidades para inserção nas cadeias globais (Capítulo I.7: Construção naval militar).",
    sectionCode: "I.7",
    chapterTitle: "Construção naval militar",
    detailCode: "I.7.8",
    itemTitle: "Oportunidades para inserção nas cadeias globais",
    rawSectionTitle: "7.8. Problemas sistêmicos e lições para uma nova política de desenvolvimento da indústria naval brasileira",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas", "G9 — Construção Militar"],
    groupCodes: ["G1", "G2", "G3", "G9"],
  },
  {
    title: "Interface: I.8.1. Direcionadores globais, metas e regulamentação internacional da descarbonização marítima (G1 + G2 + G8 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G8 — Descarbonização, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.8.1. Direcionadores globais, metas e regulamentação internacional da descarbonização marítima (Capítulo I.8: Descarbonização na Indústria Marítima).",
    sectionCode: "I.8",
    chapterTitle: "Descarbonização na Indústria Marítima",
    detailCode: "I.8.1",
    itemTitle: "Direcionadores globais, metas e regulamentação internacional da descarbonização marítima",
    rawSectionTitle: "8.1. Transformações geopolíticas e seus impactos sobre o comércio, o transporte marítimo e a indústria naval",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G2", "G8", "G3"],
  },
  {
    title: "Interface: I.8.2. Estratégias de descarbonização nos principais países e regiões (G1 + G2 + G8 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G8 — Descarbonização, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.8.2. Estratégias de descarbonização nos principais países e regiões (Capítulo I.8: Descarbonização na Indústria Marítima).",
    sectionCode: "I.8",
    chapterTitle: "Descarbonização na Indústria Marítima",
    detailCode: "I.8.2",
    itemTitle: "Estratégias de descarbonização nos principais países e regiões",
    rawSectionTitle: "8.2. Segurança econômica e reorganização das cadeias globais de produção e suprimento",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G2", "G8", "G3"],
  },
  {
    title: "Interface: I.8.3. Respostas de armadores, operadores, portos e fornecedores de energia à descarbonização (G1 + G2 + G8 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G8 — Descarbonização, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.8.3. Respostas de armadores, operadores, portos e fornecedores de energia à descarbonização (Capítulo I.8: Descarbonização na Indústria Marítima).",
    sectionCode: "I.8",
    chapterTitle: "Descarbonização na Indústria Marítima",
    detailCode: "I.8.3",
    itemTitle: "Respostas de armadores, operadores, portos e fornecedores de energia à descarbonização",
    rawSectionTitle: "8.3. Descarbonização e novas exigências ambientais: impactos sobre a demanda e a estrutura da indústria naval",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G2", "G8", "G3"],
  },
  {
    title: "Interface: I.8.4. Combustíveis marítimos alternativos: características, disponibilidade, custos e perspectivas (G1 + G2 + G8 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G8 — Descarbonização, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.8.4. Combustíveis marítimos alternativos: características, disponibilidade, custos e perspectivas (Capítulo I.8: Descarbonização na Indústria Marítima).",
    sectionCode: "I.8",
    chapterTitle: "Descarbonização na Indústria Marítima",
    detailCode: "I.8.4",
    itemTitle: "Combustíveis marítimos alternativos: características, disponibilidade, custos e perspectivas",
    rawSectionTitle: "8.4. Reconfiguração da indústria naval mundial: relocalização de capacidades produtivas, políticas de reindustrialização e novos países produtores",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G2", "G8", "G3"],
  },
  {
    title: "Interface: I.8.5. Tecnologias de eficiência energética e redução de emissões: casco, propulsão, sistemas de controle e digitalização (G1 + G2 + G8 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G8 — Descarbonização, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.8.5. Tecnologias de eficiência energética e redução de emissões: casco, propulsão, sistemas de controle e digitalização (Capítulo I.8: Descarbonização na Indústria Marítima).",
    sectionCode: "I.8",
    chapterTitle: "Descarbonização na Indústria Marítima",
    detailCode: "I.8.5",
    itemTitle: "Tecnologias de eficiência energética e redução de emissões: casco, propulsão, sistemas de controle e digitalização",
    rawSectionTitle: "8.5. Segurança e defesa e seus impactos sobre a indústria naval",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G2", "G8", "G3"],
  },
  {
    title: "Interface: I.8.6. Maturidade tecnológica, custos e perspectivas de adoção das tecnologias de descarbonização (G1 + G2 + G8 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G8 — Descarbonização, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item I.8.6. Maturidade tecnológica, custos e perspectivas de adoção das tecnologias de descarbonização (Capítulo I.8: Descarbonização na Indústria Marítima).",
    sectionCode: "I.8",
    chapterTitle: "Descarbonização na Indústria Marítima",
    detailCode: "I.8.6",
    itemTitle: "Maturidade tecnológica, custos e perspectivas de adoção das tecnologias de descarbonização",
    rawSectionTitle: "8.6. Riscos e oportunidades decorrentes das transformações geopolíticas e ambientais para a indústria naval brasileira",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G8 — Descarbonização", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G2", "G8", "G3"],
  },
  {
    title: "Interface: II.9.1. Impactos da descarbonização sobre o projeto, a construção e o retrofitting de navios (G1 + G2 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.9.1. Impactos da descarbonização sobre o projeto, a construção e o retrofitting de navios (Capítulo I.9: None).",
    sectionCode: "I.9",
    chapterTitle: null,
    detailCode: "II.9.1",
    itemTitle: "Impactos da descarbonização sobre o projeto, a construção e o retrofitting de navios",
    rawSectionTitle: "9.1. Condições econômicas para o desenvolvimento da indústria marítima brasileira: demanda, ambiente macroeconômico, custo de capital, restrições fiscais, taxa de câmbio e ambiente de investimento",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G2", "G3"],
  },
  {
    title: "Interface: II.9.2. Competências requeridas para projeto e construção de navios capazes ou preparados para novos combustíveis (G1 + G2 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.9.2. Competências requeridas para projeto e construção de navios capazes ou preparados para novos combustíveis (Capítulo I.9: None).",
    sectionCode: "I.9",
    chapterTitle: null,
    detailCode: "II.9.2",
    itemTitle: "Competências requeridas para projeto e construção de navios capazes ou preparados para novos combustíveis",
    rawSectionTitle: "9.2. Organização institucional dos órgãos do Estado com atribuições sobre a indústria marítima",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G2", "G3"],
  },
  {
    title: "Interface: II.9.3. Competências requeridas para desenvolvimento e aplicação de tecnologias de eficiência energética, captura de carbono e correlatas (G1 + G2 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.9.3. Competências requeridas para desenvolvimento e aplicação de tecnologias de eficiência energética, captura de carbono e correlatas (Capítulo I.9: None).",
    sectionCode: "I.9",
    chapterTitle: null,
    detailCode: "II.9.3",
    itemTitle: "Competências requeridas para desenvolvimento e aplicação de tecnologias de eficiência energética, captura de carbono e correlatas",
    rawSectionTitle: "9.3. Coordenação entre órgãos e políticas e continuidade da orientação programática",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G2", "G3"],
  },
  {
    title: "Interface: II.9.4. Requisitos tecnológicos e produtivos para retrofitting de navios (G1 + G2 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.9.4. Requisitos tecnológicos e produtivos para retrofitting de navios (Capítulo I.9: None).",
    sectionCode: "I.9",
    chapterTitle: null,
    detailCode: "II.9.4",
    itemTitle: "Requisitos tecnológicos e produtivos para retrofitting de navios",
    rawSectionTitle: "9.4. Capacitação técnica, autonomia decisória e continuidade institucional dos órgãos e agências",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G2", "G3"],
  },
  {
    title: "Interface: II.9.5. Capacidades e deficiências dos estaleiros brasileiros para atendimento às novas demandas tecnológicas (G1 + G2 + G3)",
    description: "Interface técnica e temática identificada no plano de atividades entre G1 — Sistematização (líder/origem) e G2 — Política Industrial e Cadeia de Suprimentos, G3 — Transporte Marítimo Brasil e Políticas Marítimas (envolvidos) para a elaboração e compatibilização do item II.9.5. Capacidades e deficiências dos estaleiros brasileiros para atendimento às novas demandas tecnológicas (Capítulo I.9: None).",
    sectionCode: "I.9",
    chapterTitle: null,
    detailCode: "II.9.5",
    itemTitle: "Capacidades e deficiências dos estaleiros brasileiros para atendimento às novas demandas tecnológicas",
    rawSectionTitle: "9.5. Riscos políticos, econômicos, institucionais e regulatórios para a reestruturação da indústria naval",
    tome: "Tomo I",
    interfaceType: "escopo sobreposto" as const,
    leadGroupName: "G1 — Sistematização",
    involvedGroupNames: ["G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    allGroupNames: ["G1 — Sistematização", "G2 — Política Industrial e Cadeia de Suprimentos", "G3 — Transporte Marítimo Brasil e Políticas Marítimas"],
    groupCodes: ["G1", "G2", "G3"],
  },
] as const;
