export const STUDY_SECTION_DESCRIPTIONS = {
  AP: "Apresentação geral do Estudo, com objetivo, metodologia e equipe; estrutura do Portal e do Relatório; banco de dados; audiovisual; sumário executivo; e conteúdo previsto para os Relatórios 1 e 2.",
  "I.1": "Apresenta os objetivos de diagnóstico e cenários do Relatório 1; a evolução da indústria naval brasileira, especialmente nos ciclos de 1970–1980 e 2000–2010; seus sucessos e falhas; e o escopo de construção de navios e embarcações fluviais, offshore, fabricação e integração de módulos, reparo, descomissionamento e desmantelamento. Explica ainda a perspectiva complementar dos quatro tomos.",
  "I.2": "Analisa indústria naval, marinha mercante, óleo e gás, geração de energia, pesca e defesa; a inter-relação entre esses setores; a natureza estratégica da economia do mar; os segmentos geradores de demanda; mudanças econômicas, tecnológicas, geopolíticas, ambientais e regulatórias; reorganização das cadeias globais; regionalização produtiva; transição energética; e oportunidades e desafios para o Brasil.",
  "I.3": "Abrange estrutura, organização e regulação dos mercados internacionais; granéis líquidos, gás, químicos, granéis sólidos, contêineres e outros segmentos; fluxos, navios, bandeiras, tecnologia, fretes, preços e carteiras de encomendas; navegação e meio ambiente; evolução das frotas; tendências; cenários de demanda; e desafios e oportunidades para a marinha mercante e a indústria naval no Brasil.",
  "I.4": "Examina a evolução da marinha mercante brasileira; cabotagem e longo curso; regulamentação e organização dos mercados; infraestrutura; empresas, frotas, bandeiras e afretamento; integração às redes globais; apoio portuário e apoio marítimo como segmento da navegação brasileira; custos da bandeira brasileira; setor pesqueiro; e cenários de demanda para construção, reparo, conversão e modernização.",
  "I.5": "Analisa as principais bacias e sua infraestrutura; fluxos de carga; empresas e frotas; transporte multimodal; navegação fluvial de percurso internacional; impactos ambientais; transporte de passageiros na Amazônia; transporte hidroviário urbano; desenvolvimento regional; e cenários de demanda para construção de embarcações fluviais.",
  "I.6": "Examina a evolução e as perspectivas do óleo e gás offshore no mundo e no Brasil; regiões, empresas, países, marcos regulatórios e unidades de exploração e produção; mercados de FPSO e sondas; construção, afretamento, módulos, conversão e descomissionamento; navios aliviadores e OSV; e geração eólica offshore, suas instalações, embarcações especializadas e cenários de demanda.",
  "I.7": "Analisa a evolução e as perspectivas dos programas de construção naval militar no Brasil; experiências internacionais relevantes; programas de offset, conteúdo local, clusters produtivos, capacitação tecnológica e inovação; e cenários de demanda por navios e embarcações militares.",
  "I.8": "Avalia o processo de descarbonização da indústria marítima; metas da IMO e estratégias nacionais e regionais; respostas de armadores, operadores, portos e fornecedores de energia; tecnologias emergentes e eficiência energética; infraestrutura de abastecimento; combustíveis alternativos; novas embarcações e retrofitting; potencial brasileiro em combustíveis renováveis; e infraestrutura portuária e logística verde.",
  "II.1": "Analisa a trajetória e a estrutura atual da construção naval mundial; produção; capacidade instalada por país, classe de estaleiro e segmento; principais grupos e estaleiros; especialização e seriação; navios, apoio marítimo, offshore e defesa; protecionismo; competitividade; tecnologia; cadeia produtiva; mercados; e impactos ambientais, tecnológicos e geopolíticos recentes.",
  "II.2": "Dimensões de análise das experiências nacionais: protecionismo; evolução da indústria; estrutura empresarial; especialização; qualificação tecnológica; recursos humanos; cadeia de fornecedores; inserção internacional; evolução da produtividade; competitividade; resultados produtivos; estratégias de desenvolvimento tecnológico e catching-up.",
  "II.3": "Examina a história e a evolução da indústria naval e offshore brasileira; planos e programas; ciclos de expansão e retração; unidades offshore, construção militar e embarcações fluviais; trajetória de empresas, capacidade produtiva e cadeia de fornecedores; desempenho; tecnologia e recursos humanos; contratos, preços e prazos; distribuição geográfica; e fatores econômicos, empresariais, tecnológicos, regulatórios e institucionais.",
  "II.4": "Realiza diagnóstico de infraestrutura, capacidade produtiva, produtividade, tecnologia, suprimentos e modernização dos estaleiros brasileiros; levanta estaleiros e instalações de fabricação e integração de módulos, em operação ou não; examina organização, carteiras, engenharia, processos, gestão e cadeia produtiva por tipo de produto e região; e avalia o potencial de reativação ou adaptação, incluindo visitas de campo.",
  "II.5": "Analisa o mercado mundial, tendências e regulação de reparo, conversão, desmantelamento e descomissionamento; diferenças entre estaleiros e instalações; demanda e capacidade nacional para reparo, docagem, conversão e modernização; competição internacional; retrofitting; desmantelamento; desafios e oportunidades.",
  "II.6": "Examina a nacionalização de componentes nos principais países; a importância das indústrias siderúrgica e de materiais, equipamentos e sistemas navais; a evolução do conteúdo nacional no Brasil; localização e capacidade dos fornecedores; dependências externas; lacunas produtivas e tecnológicas; relações entre estaleiros e fornecedores; e diferenças entre as cadeias civil, fluvial, offshore e militar.",
  "II.7": "Avalia a capacitação dos estaleiros em engenharia de produtos, processos e gestão da produção; o perfil da força de trabalho básica, técnica e gerencial; as capacidades de pesquisa, desenvolvimento e inovação em empresas, universidades e centros; as relações com a base produtiva; e a disponibilidade e a formação de recursos humanos operacional, técnico, de engenharia e gerencial.",
  "II.8": "Define metodologia de avaliação tecnológica, indicadores de desempenho e benchmarking; compara padrões tecnológicos, produtividade e desempenho de classes de estaleiros mundiais; analisa os estaleiros brasileiros em sua operação passada, situação atual e potencial; e identifica possibilidades de inserção competitiva, limitações, gargalos e metas.",
  "II.9": "Sintetiza mudanças de mercado e tendências tecnológicas da descarbonização analisadas no Tomo I e seus impactos sobre projeto, construção, conversão e reparo; avalia competências requeridas para novos combustíveis, eficiência energética, captura de carbono e tecnologias correlatas; capacidades e deficiências brasileiras; descarbonização dos processos construtivos; e desafios e oportunidades para estaleiros, empresas de engenharia e fornecedores.",
  "III.1": "Reúne literatura, conceitos e justificativas econômicas da política industrial; políticas horizontais e setoriais; transformações ambientais e geopolíticas; papel de organizações multilaterais; evolução da política industrial brasileira; fundamentos das políticas marítima e naval; metodologia de análise setorial; instrumentos horizontais, incluindo a Nova Indústria Brasil; políticas de descarbonização; desafios regulatórios; novos combustíveis; e possibilidades para o Brasil na transição energética marítima.",
  "III.2": "Examina justificativas e evolução das políticas de marinha mercante desde o pós-guerra; modelos de proteção e incentivo; regulação nacional, internacional, bilateral e multilateral; casos internacionais relevantes; registros alternativos; financiamento, subsídios e incentivos fiscais; reservas de mercado e carga; preferência de bandeira; tripulação; desenvolvimento tecnológico; e resultados sobre frota, participação de mercado e competitividade.",
  "III.3": "Dimensões de análise das experiências nacionais: planejamento e políticas de desenvolvimento da indústria; proteção do mercado; participação e controle estatal; subsídios e incentivos fiscais; financiamento; garantias e créditos à exportação; compras governamentais; políticas de conteúdo local; desenvolvimento tecnológico e transferência de tecnologia; cooperação internacional; impacto das políticas governamentais na consolidação da indústria; identificação dos casos mais expressivos de sucesso e falha.",
  "III.4": "Abrange a evolução das políticas brasileiras de marinha mercante, construção naval, navegação interior, óleo e gás offshore, energias oceânicas e defesa; suas inter-relações; Planos de Desenvolvimento e de Construção Naval; ciclos de 1970–1980 e 2000–2010; reserva de mercado e carga, preferência de bandeira, tripulação, financiamento, incentivos fiscais, conteúdo local e compras governamentais; FMM; resultados; BR do Mar; e legislação tributária.",
  "III.5": "Examina a história e a relevância do Fundo da Marinha Mercante; AFRMM e FMM; estrutura institucional, agentes financeiros e concessão; arrecadação, distribuição e aplicação de recursos; eficiência de projetos e eficácia do sistema; contas vinculadas; custo efetivo de capital; simulações; riscos, garantias e custos financeiros; efeitos distributivos; navegação interior; desenvolvimento regional; e alterações do BR do Mar.",
  "III.6": "Analisa políticas industriais e nacionalização nos principais países produtores; conteúdo local; siderurgia, materiais e equipamentos navais; articulação entre políticas de fornecedores e estaleiros; histórico, estrutura, empresas, localização, capacidade, tecnologia, recursos humanos e dependências de importação no Brasil; evolução dos índices de nacionalização; cenários prospectivos; desafios e oportunidades para a cadeia nacional de suprimentos.",
  "III.7": "Analisa os ciclos brasileiros de expansão das décadas de 1970 e 1980 e de 2000 e 2010, seus objetivos, instrumentos, resultados, fatores endógenos e exógenos de crise e queda e comparações com Coreia do Sul e China; avalia continuidade e coordenação institucional, demanda, financiamento, escala, produtividade, aprendizado tecnológico e inserção internacional; e identifica problemas sistêmicos e lições para uma nova política naval.",
  "III.8": "Sintetiza as transformações geopolíticas e ambientais que afetam mercados e indústria naval; mudanças em energia, navegação e defesa; reorganização de cadeias produtivas, segurança econômica, transição energética e exigências ambientais; impactos sobre distribuição geográfica da produção, acesso a mercados e tecnologias, demanda e parcerias internacionais; e riscos, desafios e oportunidades para a reestruturação da indústria naval brasileira.",
  "III.9": "Avalia as condições econômicas da indústria marítima brasileira, incluindo volume e estabilidade da demanda, macroeconomia, custo de capital, restrições fiscais, câmbio e ambiente de investimento; a organização, coordenação, capacitação, autonomia e continuidade dos órgãos e agências do Estado; riscos políticos, econômicos e regulatórios; e aspectos para reorientar políticas e novos modelos nas interfaces com marinha mercante, óleo e gás, defesa e energia.",
  "IV.1": "Consolida os resultados dos Tomos I, II e III e articula mercados e demanda, capacidade produtiva, tecnologia, produtividade, competitividade, cadeia de suprimentos, políticas e ambiente institucional. Analisa volume e estabilidade da demanda, capacidade dos estaleiros, custos, prazos, qualidade, financiamento, potencialidades, limitações, dependências, gargalos, sinergias, transição energética, mudanças geopolíticas e variáveis críticas para os cenários.",
  "IV.2": "Consolida projeções de demanda de transporte marítimo, navegação interior, óleo e gás offshore, energias oceânicas, defesa, reparo e descomissionamento. Define cenários alternativos, hipóteses, horizontes e incertezas; simula custos, prazos, qualidade, confiabilidade, financiamento, tributação, regras de bandeira, afretamento, conteúdo local e incentivos; e avalia competitividade, recursos humanos, tecnologia, investimentos, cadeia de suprimentos e potencial de produção nacional.",
  "IV.3": "Sintetiza as conclusões do diagnóstico integrado e dos cenários, incluindo potencialidades, limitações, gargalos e condições para o desenvolvimento competitivo da indústria naval. Explicita evidências, incertezas, hipóteses e lacunas; indica questões para identificar segmentos estratégicos, formular políticas e elaborar o Plano de Ação; e delimita os temas do Relatório 2.",
} as const;

export type StudySectionCode = keyof typeof STUDY_SECTION_DESCRIPTIONS;

export function studySectionDescription(code: string): string {
  return STUDY_SECTION_DESCRIPTIONS[code as StudySectionCode] ?? "";
}
